// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rbconsult-bh/saftaja/khazina/internal/domain"
	"github.com/shopspring/decimal"
)

const createGatewayAccount = `-- name: CreateGatewayAccount :one
INSERT INTO gateway_accounts (project_id, connector_type, account_name, credentials, settings, payment_methods, is_active)
VALUES ($1, $2, $3, $4, $5, $6, true) RETURNING id, project_id, connector_type, account_name, settings, payment_methods, is_active, created_at, updated_at, deleted_at, credentials
`

type CreateGatewayAccountParams struct {
	ProjectID      uuid.UUID
	ConnectorType  domain.ConnectorType
	AccountName    string
	Credentials    []byte
	Settings       []byte
	PaymentMethods []byte
}

func (q *Queries) CreateGatewayAccount(ctx context.Context, arg CreateGatewayAccountParams) (GatewayAccount, error) {
	row := q.db.QueryRow(ctx, createGatewayAccount,
		arg.ProjectID,
		arg.ConnectorType,
		arg.AccountName,
		arg.Credentials,
		arg.Settings,
		arg.PaymentMethods,
	)
	var i GatewayAccount
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ConnectorType,
		&i.AccountName,
		&i.Settings,
		&i.PaymentMethods,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Credentials,
	)
	return i, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (project_id, amount, currency, customer_email, customer_name, description, status)
VALUES ($1, $2, $3, $4, $5, $6, 'pending') RETURNING id, project_id, amount, currency, status, external_id, customer_email, customer_name, description, paid_at, created_at, updated_at, deleted_at
`

type CreateInvoiceParams struct {
	ProjectID     uuid.UUID
	Amount        decimal.Decimal
	Currency      string
	CustomerEmail pgtype.Text
	CustomerName  pgtype.Text
	Description   pgtype.Text
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.ProjectID,
		arg.Amount,
		arg.Currency,
		arg.CustomerEmail,
		arg.CustomerName,
		arg.Description,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ExternalID,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.Description,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name) VALUES ($1) RETURNING id, name, created_at, updated_at, deleted_at
`

func (q *Queries) CreateOrganization(ctx context.Context, name string) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (organization_id, name, environment, custom_domain)
VALUES ($1, $2, $3, $4) RETURNING id, organization_id, name, environment, custom_domain, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	OrganizationID uuid.UUID
	Name           string
	Environment    domain.ProjectEnvironment
	CustomDomain   pgtype.Text
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OrganizationID,
		arg.Name,
		arg.Environment,
		arg.CustomDomain,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Environment,
		&i.CustomDomain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
