// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_intent.sql

package store

import (
	"context"
)

const createAuthIntent = `-- name: CreateAuthIntent :exec
INSERT INTO auth_intent (email, token_hash, expires_at, created_at)
VALUES ($1, $2, NOW() + INTERVAL '15 minutes', NOW())
ON CONFLICT (email)
	DO UPDATE
	SET token_hash = $2
`

type CreateAuthIntentParams struct {
	Email     string
	TokenHash []byte
}

func (q *Queries) CreateAuthIntent(ctx context.Context, arg CreateAuthIntentParams) error {
	_, err := q.db.Exec(ctx, createAuthIntent, arg.Email, arg.TokenHash)
	return err
}

const isTokenHashValid = `-- name: IsTokenHashValid :one
SELECT EXISTS (
    SELECT 1
    FROM auth_intent
    WHERE token_hash = $1
    AND expires_at > NOW()
)
`

func (q *Queries) IsTokenHashValid(ctx context.Context, tokenHash []byte) (bool, error) {
	row := q.db.QueryRow(ctx, isTokenHashValid, tokenHash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
