// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_intent.sql

package store

import (
	"context"
)

const createAuthIntent = `-- name: CreateAuthIntent :exec
INSERT INTO auth_intent (email, token_hash, expires_at, created_at)
VALUES ($1, $2, NOW() + INTERVAL '15 minutes', NOW())
`

type CreateAuthIntentParams struct {
	Email     string
	TokenHash []byte
}

func (q *Queries) CreateAuthIntent(ctx context.Context, arg CreateAuthIntentParams) error {
	_, err := q.db.Exec(ctx, createAuthIntent, arg.Email, arg.TokenHash)
	return err
}
