// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_intent.sql

package store

import (
	"context"
)

const consumeAuthIntentByTokenHash = `-- name: ConsumeAuthIntentByTokenHash :one
DELETE FROM auth_intent
WHERE token_hash = $1
  AND expires_at > NOW()
RETURNING email
`

func (q *Queries) ConsumeAuthIntentByTokenHash(ctx context.Context, tokenHash []byte) (string, error) {
	row := q.db.QueryRow(ctx, consumeAuthIntentByTokenHash, tokenHash)
	var email string
	err := row.Scan(&email)
	return email, err
}

const createAuthIntent = `-- name: CreateAuthIntent :exec
INSERT INTO auth_intent (email, token_hash, expires_at)
VALUES ($1, $2, NOW() + INTERVAL '15 minutes')
ON CONFLICT (email)
	DO UPDATE
	SET token_hash = $2,
      expires_at = NOW() + INTERVAL '15 minutes'
`

type CreateAuthIntentParams struct {
	Email     string
	TokenHash []byte
}

func (q *Queries) CreateAuthIntent(ctx context.Context, arg CreateAuthIntentParams) error {
	_, err := q.db.Exec(ctx, createAuthIntent, arg.Email, arg.TokenHash)
	return err
}
