// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer_session.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createCustomerSession = `-- name: CreateCustomerSession :one
INSERT INTO customer_session (customer_id, current_jti_hash, expires_at)
VALUES ($1, $2, NOW() + INTERVAL '30 days')
RETURNING id, customer_id, current_jti_hash, expires_at, created_at
`

type CreateCustomerSessionParams struct {
	CustomerID     uuid.UUID
	CurrentJtiHash []byte
}

func (q *Queries) CreateCustomerSession(ctx context.Context, arg CreateCustomerSessionParams) (CustomerSession, error) {
	row := q.db.QueryRow(ctx, createCustomerSession, arg.CustomerID, arg.CurrentJtiHash)
	var i CustomerSession
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CurrentJtiHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCustomerSessionByIDAndCustomerID = `-- name: DeleteCustomerSessionByIDAndCustomerID :exec
DELETE FROM customer_session
WHERE id = $1 AND customer_id = $2
`

type DeleteCustomerSessionByIDAndCustomerIDParams struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
}

func (q *Queries) DeleteCustomerSessionByIDAndCustomerID(ctx context.Context, arg DeleteCustomerSessionByIDAndCustomerIDParams) error {
	_, err := q.db.Exec(ctx, deleteCustomerSessionByIDAndCustomerID, arg.ID, arg.CustomerID)
	return err
}
