// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomerIfNotExists = `-- name: CreateCustomerIfNotExists :one
INSERT INTO customer (name, email)
VALUES ($1, $2)
ON CONFLICT (email) DO UPDATE SET email = customer.email
RETURNING id, name, email, created_at, updated_at, deleted_at, (xmax != 0) as is_new_customer
`

type CreateCustomerIfNotExistsParams struct {
	Name  string
	Email string
}

type CreateCustomerIfNotExistsRow struct {
	ID            uuid.UUID
	Name          string
	Email         string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	IsNewCustomer bool
}

func (q *Queries) CreateCustomerIfNotExists(ctx context.Context, arg CreateCustomerIfNotExistsParams) (CreateCustomerIfNotExistsRow, error) {
	row := q.db.QueryRow(ctx, createCustomerIfNotExists, arg.Name, arg.Email)
	var i CreateCustomerIfNotExistsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsNewCustomer,
	)
	return i, err
}
