// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomerIfNotExists = `-- name: CreateCustomerIfNotExists :one
WITH upserted AS (
  INSERT INTO customer (name, email)
  VALUES ($1, $2)
  ON CONFLICT (email) DO UPDATE SET email = customer.email
  RETURNING id, name, email, created_at, updated_at, deleted_at
)
SELECT 
  upserted.id, upserted.name, upserted.email, upserted.created_at, upserted.updated_at, upserted.deleted_at,
  NOT EXISTS (
    SELECT 1 FROM organization_customer 
    WHERE customer_id = upserted.id
  ) AS needs_default_org
FROM upserted
`

type CreateCustomerIfNotExistsParams struct {
	Name  string
	Email string
}

type CreateCustomerIfNotExistsRow struct {
	ID              uuid.UUID
	Name            string
	Email           string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	NeedsDefaultOrg bool
}

func (q *Queries) CreateCustomerIfNotExists(ctx context.Context, arg CreateCustomerIfNotExistsParams) (CreateCustomerIfNotExistsRow, error) {
	row := q.db.QueryRow(ctx, createCustomerIfNotExists, arg.Name, arg.Email)
	var i CreateCustomerIfNotExistsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.NeedsDefaultOrg,
	)
	return i, err
}
