// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gateway_accounts.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGatewayAccount = `-- name: CreateGatewayAccount :one
INSERT INTO gateway_accounts (project_id, connector_type, account_name, secret, config, is_active)
VALUES ($1, $2, $3, $4, $5, true) RETURNING id, project_id, connector_type, account_name, config, is_active, created_at, updated_at, deleted_at, secret
`

type CreateGatewayAccountParams struct {
	ProjectID     uuid.UUID
	ConnectorType ConnectorType
	AccountName   string
	Secret        []byte
	Config        []byte
}

func (q *Queries) CreateGatewayAccount(ctx context.Context, arg CreateGatewayAccountParams) (GatewayAccount, error) {
	row := q.db.QueryRow(ctx, createGatewayAccount,
		arg.ProjectID,
		arg.ConnectorType,
		arg.AccountName,
		arg.Secret,
		arg.Config,
	)
	var i GatewayAccount
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ConnectorType,
		&i.AccountName,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Secret,
	)
	return i, err
}

const getGatewayAccount = `-- name: GetGatewayAccount :one
SELECT id, project_id, connector_type, account_name, config, is_active, created_at, updated_at, deleted_at, secret FROM gateway_accounts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGatewayAccount(ctx context.Context, id uuid.UUID) (GatewayAccount, error) {
	row := q.db.QueryRow(ctx, getGatewayAccount, id)
	var i GatewayAccount
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ConnectorType,
		&i.AccountName,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Secret,
	)
	return i, err
}

const getGatewayAccountByIDAndProject = `-- name: GetGatewayAccountByIDAndProject :one
SELECT id, project_id, connector_type, account_name, config, is_active, created_at, updated_at, deleted_at, secret FROM gateway_accounts
WHERE id = $1 AND project_id = $2 LIMIT 1
`

type GetGatewayAccountByIDAndProjectParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetGatewayAccountByIDAndProject(ctx context.Context, arg GetGatewayAccountByIDAndProjectParams) (GatewayAccount, error) {
	row := q.db.QueryRow(ctx, getGatewayAccountByIDAndProject, arg.ID, arg.ProjectID)
	var i GatewayAccount
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ConnectorType,
		&i.AccountName,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Secret,
	)
	return i, err
}

const getGatewayAccountByPaymentIntentID = `-- name: GetGatewayAccountByPaymentIntentID :one
SELECT ga.id, ga.project_id, connector_type, account_name, config, is_active, ga.created_at, ga.updated_at, ga.deleted_at, secret, pi.id, invoice_id, pi.project_id, gateway_account_id, gateway_session_id, status, payment_method, payer_ip, payer_user_agent, expires_at, pi.created_at, pi.updated_at, pi.deleted_at, idempotency_key FROM gateway_accounts ga
JOIN payment_intents pi ON ga.id = pi.gateway_account_id
WHERE pi.id = $1
`

type GetGatewayAccountByPaymentIntentIDRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	ConnectorType    ConnectorType
	AccountName      string
	Config           []byte
	IsActive         bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	Secret           []byte
	ID_2             uuid.UUID
	InvoiceID        uuid.UUID
	ProjectID_2      uuid.UUID
	GatewayAccountID uuid.UUID
	GatewaySessionID *string
	Status           PaymentIntentStatus
	PaymentMethod    PaymentMethod
	PayerIp          string
	PayerUserAgent   string
	ExpiresAt        pgtype.Timestamptz
	CreatedAt_2      pgtype.Timestamptz
	UpdatedAt_2      pgtype.Timestamptz
	DeletedAt_2      pgtype.Timestamptz
	IdempotencyKey   string
}

func (q *Queries) GetGatewayAccountByPaymentIntentID(ctx context.Context, id uuid.UUID) (GetGatewayAccountByPaymentIntentIDRow, error) {
	row := q.db.QueryRow(ctx, getGatewayAccountByPaymentIntentID, id)
	var i GetGatewayAccountByPaymentIntentIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ConnectorType,
		&i.AccountName,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Secret,
		&i.ID_2,
		&i.InvoiceID,
		&i.ProjectID_2,
		&i.GatewayAccountID,
		&i.GatewaySessionID,
		&i.Status,
		&i.PaymentMethod,
		&i.PayerIp,
		&i.PayerUserAgent,
		&i.ExpiresAt,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
		&i.DeletedAt_2,
		&i.IdempotencyKey,
	)
	return i, err
}

const listActiveGatewayAccounts = `-- name: ListActiveGatewayAccounts :many
SELECT id, project_id, connector_type, account_name, config, is_active, created_at, updated_at, deleted_at, secret FROM gateway_accounts
WHERE project_id = $1
AND is_active = true
AND deleted_at IS NULL
`

func (q *Queries) ListActiveGatewayAccounts(ctx context.Context, projectID uuid.UUID) ([]GatewayAccount, error) {
	rows, err := q.db.Query(ctx, listActiveGatewayAccounts, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GatewayAccount
	for rows.Next() {
		var i GatewayAccount
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ConnectorType,
			&i.AccountName,
			&i.Config,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Secret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
