// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoices.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (project_id, amount, currency, customer_email, customer_name, description, status)
VALUES ($1, $2, $3, $4, $5, $6, 'pending') RETURNING id, project_id, amount, currency, status, external_id, customer_email, customer_name, description, paid_at, created_at, updated_at, deleted_at
`

type CreateInvoiceParams struct {
	ProjectID     uuid.UUID
	Amount        decimal.Decimal
	Currency      string
	CustomerEmail *string
	CustomerName  *string
	Description   *string
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.ProjectID,
		arg.Amount,
		arg.Currency,
		arg.CustomerEmail,
		arg.CustomerName,
		arg.Description,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ExternalID,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.Description,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, project_id, amount, currency, status, external_id, customer_email, customer_name, description, paid_at, created_at, updated_at, deleted_at FROM invoices WHERE id = $1
`

func (q *Queries) GetInvoiceByID(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ExternalID,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.Description,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInvoiceByIDAndProject = `-- name: GetInvoiceByIDAndProject :one
SELECT id, project_id, amount, currency, status, external_id, customer_email, customer_name, description, paid_at, created_at, updated_at, deleted_at FROM invoices WHERE id = $1 AND project_id = $2
`

type GetInvoiceByIDAndProjectParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetInvoiceByIDAndProject(ctx context.Context, arg GetInvoiceByIDAndProjectParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByIDAndProject, arg.ID, arg.ProjectID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ExternalID,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.Description,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInvoiceByIDAndProjectForNoKeyUpdate = `-- name: GetInvoiceByIDAndProjectForNoKeyUpdate :one
SELECT id, project_id, amount, currency, status, external_id, customer_email, customer_name, description, paid_at, created_at, updated_at, deleted_at FROM invoices
WHERE id = $1 AND project_id = $2
FOR NO KEY UPDATE
`

type GetInvoiceByIDAndProjectForNoKeyUpdateParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetInvoiceByIDAndProjectForNoKeyUpdate(ctx context.Context, arg GetInvoiceByIDAndProjectForNoKeyUpdateParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByIDAndProjectForNoKeyUpdate, arg.ID, arg.ProjectID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ExternalID,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.Description,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInvoiceWithItemsByIDAndProjectID = `-- name: GetInvoiceWithItemsByIDAndProjectID :many
SELECT i.id, i.project_id, i.amount, i.currency, i.status, i.external_id, i.customer_email, i.customer_name, i.description, i.paid_at, i.created_at, i.updated_at, i.deleted_at, ii.id, ii.invoice_id, ii.name, ii.description, ii.quantity, ii.unit_price, ii.amount, ii.created_at
FROM invoices i
JOIN invoice_items ii ON ii.invoice_id = i.id
WHERE i.id = $1 AND i.project_id = $2
`

type GetInvoiceWithItemsByIDAndProjectIDParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

type GetInvoiceWithItemsByIDAndProjectIDRow struct {
	Invoice     Invoice
	InvoiceItem InvoiceItem
}

func (q *Queries) GetInvoiceWithItemsByIDAndProjectID(ctx context.Context, arg GetInvoiceWithItemsByIDAndProjectIDParams) ([]GetInvoiceWithItemsByIDAndProjectIDRow, error) {
	rows, err := q.db.Query(ctx, getInvoiceWithItemsByIDAndProjectID, arg.ID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInvoiceWithItemsByIDAndProjectIDRow
	for rows.Next() {
		var i GetInvoiceWithItemsByIDAndProjectIDRow
		if err := rows.Scan(
			&i.Invoice.ID,
			&i.Invoice.ProjectID,
			&i.Invoice.Amount,
			&i.Invoice.Currency,
			&i.Invoice.Status,
			&i.Invoice.ExternalID,
			&i.Invoice.CustomerEmail,
			&i.Invoice.CustomerName,
			&i.Invoice.Description,
			&i.Invoice.PaidAt,
			&i.Invoice.CreatedAt,
			&i.Invoice.UpdatedAt,
			&i.Invoice.DeletedAt,
			&i.InvoiceItem.ID,
			&i.InvoiceItem.InvoiceID,
			&i.InvoiceItem.Name,
			&i.InvoiceItem.Description,
			&i.InvoiceItem.Quantity,
			&i.InvoiceItem.UnitPrice,
			&i.InvoiceItem.Amount,
			&i.InvoiceItem.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvoiceFailed = `-- name: MarkInvoiceFailed :exec
UPDATE invoices SET status = 'failed' WHERE id = $1
`

func (q *Queries) MarkInvoiceFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markInvoiceFailed, id)
	return err
}

const markInvoicePaid = `-- name: MarkInvoicePaid :exec
UPDATE invoices SET status = 'paid', paid_at = NOW() WHERE id = $1
`

func (q *Queries) MarkInvoicePaid(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markInvoicePaid, id)
	return err
}
