// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type OrganizationRole string

const (
	OrganizationRoleOwner  OrganizationRole = "owner"
	OrganizationRoleAdmin  OrganizationRole = "admin"
	OrganizationRoleMember OrganizationRole = "member"
)

func (e *OrganizationRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrganizationRole(s)
	case string:
		*e = OrganizationRole(s)
	default:
		return fmt.Errorf("unsupported scan type for OrganizationRole: %T", src)
	}
	return nil
}

type NullOrganizationRole struct {
	OrganizationRole OrganizationRole
	Valid            bool // Valid is true if OrganizationRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrganizationRole) Scan(value interface{}) error {
	if value == nil {
		ns.OrganizationRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrganizationRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrganizationRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrganizationRole), nil
}

type AuthIntent struct {
	ID        uuid.UUID
	Email     string
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Customer struct {
	ID        uuid.UUID
	Name      string
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type CustomerSession struct {
	ID             uuid.UUID
	CustomerID     uuid.UUID
	CurrentJtiHash []byte
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type GatewayAccount struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	ConnectorType ConnectorType
	AccountName   string
	Config        []byte
	IsActive      bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	Secret        []byte
}

type Invoice struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	Amount        decimal.Decimal
	Currency      string
	Status        InvoiceStatus
	ExternalID    pgtype.Text
	CustomerEmail pgtype.Text
	CustomerName  pgtype.Text
	Description   pgtype.Text
	PaidAt        pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type InvoiceItem struct {
	ID          uuid.UUID
	InvoiceID   uuid.UUID
	Name        string
	Description pgtype.Text
	Quantity    int32
	UnitPrice   decimal.Decimal
	Amount      decimal.Decimal
	CreatedAt   pgtype.Timestamptz
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type OrganizationCustomer struct {
	OrganizationID uuid.UUID
	CustomerID     uuid.UUID
	Role           OrganizationRole
	CreatedAt      pgtype.Timestamptz
}

type PaymentIntent struct {
	ID               uuid.UUID
	InvoiceID        uuid.UUID
	ProjectID        uuid.UUID
	GatewayAccountID uuid.UUID
	GatewaySessionID pgtype.Text
	Status           PaymentIntentStatus
	PaymentMethod    PaymentMethod
	PayerIp          pgtype.Text
	PayerUserAgent   pgtype.Text
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	IdempotencyKey   pgtype.Text
}

type Project struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Environment    ProjectEnvironment
	CustomDomain   pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type Transaction struct {
	ID                   uuid.UUID
	PaymentIntentID      uuid.UUID
	InvoiceID            uuid.UUID
	ProjectID            uuid.UUID
	TransactionType      TransactionType
	GatewayTransactionID string
	Amount               decimal.Decimal
	Currency             string
	Status               TransactionStatus
	RawRequest           []byte
	RawResponse          []byte
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
}
