// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rbconsult-bh/saftaja/internal/domain"
	"github.com/shopspring/decimal"
)

type MagicTokenType string

const (
	MagicTokenTypeAuth MagicTokenType = "auth"
)

func (e *MagicTokenType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MagicTokenType(s)
	case string:
		*e = MagicTokenType(s)
	default:
		return fmt.Errorf("unsupported scan type for MagicTokenType: %T", src)
	}
	return nil
}

type NullMagicTokenType struct {
	MagicTokenType MagicTokenType
	Valid          bool // Valid is true if MagicTokenType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMagicTokenType) Scan(value interface{}) error {
	if value == nil {
		ns.MagicTokenType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MagicTokenType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMagicTokenType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MagicTokenType), nil
}

type Customer struct {
	ID        uuid.UUID
	Name      string
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type CustomerSession struct {
	ID             uuid.UUID
	CustomerID     uuid.UUID
	CurrentJtiHash []byte
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type GatewayAccount struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	ConnectorType  domain.ConnectorType
	AccountName    string
	Settings       []byte
	PaymentMethods []byte
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	Credentials    []byte
}

type Invoice struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	Amount        decimal.Decimal
	Currency      string
	Status        domain.InvoiceStatus
	ExternalID    pgtype.Text
	CustomerEmail pgtype.Text
	CustomerName  pgtype.Text
	Description   pgtype.Text
	PaidAt        pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type InvoiceItem struct {
	ID          uuid.UUID
	InvoiceID   uuid.UUID
	Name        string
	Description pgtype.Text
	Quantity    int32
	UnitPrice   decimal.Decimal
	Amount      decimal.Decimal
	CreatedAt   pgtype.Timestamptz
}

type MagicToken struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
	TokenType  MagicTokenType
	TokenHash  []byte
	ExpiresAt  pgtype.Timestamptz
	UsedAt     pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type PaymentSession struct {
	ID               uuid.UUID
	InvoiceID        uuid.UUID
	ProjectID        uuid.UUID
	GatewayAccountID uuid.UUID
	GatewaySessionID string
	Status           domain.PaymentSessionStatus
	PaymentMethod    domain.PaymentMethod
	PayerIp          pgtype.Text
	PayerUserAgent   pgtype.Text
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	IdempotencyKey   pgtype.Text
}

type Project struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Environment    domain.ProjectEnvironment
	CustomDomain   pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type Transaction struct {
	ID                   uuid.UUID
	PaymentSessionID     uuid.UUID
	InvoiceID            uuid.UUID
	ProjectID            uuid.UUID
	TransactionType      domain.TransactionType
	GatewayTransactionID string
	Amount               decimal.Decimal
	Currency             string
	Status               domain.TransactionStatus
	RawRequest           []byte
	RawResponse          []byte
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
}
