// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createDefaultOrganizationForCustomer = `-- name: CreateDefaultOrganizationForCustomer :one
WITH new_org AS (
  INSERT INTO organizations (name)
  VALUES ($1)
  RETURNING id, name, created_at, updated_at, deleted_at
)
INSERT INTO organization_customer (organization_id, customer_id, role)
SELECT new_org.id, $2, 'owner'
FROM new_org
RETURNING organization_id
`

type CreateDefaultOrganizationForCustomerParams struct {
	Name       string
	CustomerID uuid.UUID
}

func (q *Queries) CreateDefaultOrganizationForCustomer(ctx context.Context, arg CreateDefaultOrganizationForCustomerParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createDefaultOrganizationForCustomer, arg.Name, arg.CustomerID)
	var organization_id uuid.UUID
	err := row.Scan(&organization_id)
	return organization_id, err
}
