// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_intents.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createPaymentIntent = `-- name: CreatePaymentIntent :one
INSERT INTO payment_intents (invoice_id, project_id, gateway_account_id, gateway_session_id, payment_method, payer_ip, payer_user_agent, idempotency_key)
  VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
  RETURNING id, invoice_id, project_id, gateway_account_id, gateway_session_id, status, payment_method, payer_ip, payer_user_agent, expires_at, created_at, updated_at, deleted_at, idempotency_key
`

type CreatePaymentIntentParams struct {
	InvoiceID        uuid.UUID
	ProjectID        uuid.UUID
	GatewayAccountID uuid.UUID
	GatewaySessionID *string
	PaymentMethod    PaymentMethod
	PayerIp          string
	PayerUserAgent   string
	IdempotencyKey   string
}

func (q *Queries) CreatePaymentIntent(ctx context.Context, arg CreatePaymentIntentParams) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, createPaymentIntent,
		arg.InvoiceID,
		arg.ProjectID,
		arg.GatewayAccountID,
		arg.GatewaySessionID,
		arg.PaymentMethod,
		arg.PayerIp,
		arg.PayerUserAgent,
		arg.IdempotencyKey,
	)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ProjectID,
		&i.GatewayAccountID,
		&i.GatewaySessionID,
		&i.Status,
		&i.PaymentMethod,
		&i.PayerIp,
		&i.PayerUserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getPaymentIntentByID = `-- name: GetPaymentIntentByID :one
SELECT id, invoice_id, project_id, gateway_account_id, gateway_session_id, status, payment_method, payer_ip, payer_user_agent, expires_at, created_at, updated_at, deleted_at, idempotency_key FROM payment_intents
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPaymentIntentByID(ctx context.Context, id uuid.UUID) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, getPaymentIntentByID, id)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ProjectID,
		&i.GatewayAccountID,
		&i.GatewaySessionID,
		&i.Status,
		&i.PaymentMethod,
		&i.PayerIp,
		&i.PayerUserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getPaymentIntentByIDAndProject = `-- name: GetPaymentIntentByIDAndProject :one
SELECT id, invoice_id, project_id, gateway_account_id, gateway_session_id, status, payment_method, payer_ip, payer_user_agent, expires_at, created_at, updated_at, deleted_at, idempotency_key FROM payment_intents
WHERE id = $1 AND project_id = $2 LIMIT 1
`

type GetPaymentIntentByIDAndProjectParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetPaymentIntentByIDAndProject(ctx context.Context, arg GetPaymentIntentByIDAndProjectParams) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, getPaymentIntentByIDAndProject, arg.ID, arg.ProjectID)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ProjectID,
		&i.GatewayAccountID,
		&i.GatewaySessionID,
		&i.Status,
		&i.PaymentMethod,
		&i.PayerIp,
		&i.PayerUserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getPaymentIntentByIDAndProjectAndInvoiceForUpdate = `-- name: GetPaymentIntentByIDAndProjectAndInvoiceForUpdate :one
SELECT id, invoice_id, project_id, gateway_account_id, gateway_session_id, status, payment_method, payer_ip, payer_user_agent, expires_at, created_at, updated_at, deleted_at, idempotency_key FROM payment_intents
WHERE id = $1 AND project_id = $2 AND invoice_id = $3 LIMIT 1
FOR UPDATE
`

type GetPaymentIntentByIDAndProjectAndInvoiceForUpdateParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	InvoiceID uuid.UUID
}

func (q *Queries) GetPaymentIntentByIDAndProjectAndInvoiceForUpdate(ctx context.Context, arg GetPaymentIntentByIDAndProjectAndInvoiceForUpdateParams) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, getPaymentIntentByIDAndProjectAndInvoiceForUpdate, arg.ID, arg.ProjectID, arg.InvoiceID)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ProjectID,
		&i.GatewayAccountID,
		&i.GatewaySessionID,
		&i.Status,
		&i.PaymentMethod,
		&i.PayerIp,
		&i.PayerUserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getPaymentIntentByIdempotencyKeyAndProject = `-- name: GetPaymentIntentByIdempotencyKeyAndProject :one
SELECT id, invoice_id, project_id, gateway_account_id, gateway_session_id, status, payment_method, payer_ip, payer_user_agent, expires_at, created_at, updated_at, deleted_at, idempotency_key FROM payment_intents
WHERE project_id = $1
AND idempotency_key = $2
LIMIT 1
`

type GetPaymentIntentByIdempotencyKeyAndProjectParams struct {
	ProjectID      uuid.UUID
	IdempotencyKey string
}

func (q *Queries) GetPaymentIntentByIdempotencyKeyAndProject(ctx context.Context, arg GetPaymentIntentByIdempotencyKeyAndProjectParams) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, getPaymentIntentByIdempotencyKeyAndProject, arg.ProjectID, arg.IdempotencyKey)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ProjectID,
		&i.GatewayAccountID,
		&i.GatewaySessionID,
		&i.Status,
		&i.PaymentMethod,
		&i.PayerIp,
		&i.PayerUserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const updatePaymentIntentStatus = `-- name: UpdatePaymentIntentStatus :exec
UPDATE payment_intents
SET status = $2
WHERE id = $1
`

type UpdatePaymentIntentStatusParams struct {
	ID     uuid.UUID
	Status PaymentIntentStatus
}

func (q *Queries) UpdatePaymentIntentStatus(ctx context.Context, arg UpdatePaymentIntentStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentIntentStatus, arg.ID, arg.Status)
	return err
}

const updatePaymentIntentsGatewayID = `-- name: UpdatePaymentIntentsGatewayID :exec
UPDATE payment_intents
SET gateway_session_id = $2
WHERE id = $1
`

type UpdatePaymentIntentsGatewayIDParams struct {
	ID               uuid.UUID
	GatewaySessionID *string
}

func (q *Queries) UpdatePaymentIntentsGatewayID(ctx context.Context, arg UpdatePaymentIntentsGatewayIDParams) error {
	_, err := q.db.Exec(ctx, updatePaymentIntentsGatewayID, arg.ID, arg.GatewaySessionID)
	return err
}
