// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_sessions.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rbconsult-bh/saftaja/khazina/internal/domain"
)

const createPaymentSession = `-- name: CreatePaymentSession :one
INSERT INTO payment_sessions (invoice_id, project_id, gateway_account_id, gateway_session_id, payment_method, payer_ip, payer_user_agent, idempotency_key)
  VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
  RETURNING id, invoice_id, project_id, gateway_account_id, gateway_session_id, status, payment_method, payer_ip, payer_user_agent, expires_at, created_at, updated_at, deleted_at, idempotency_key
`

type CreatePaymentSessionParams struct {
	InvoiceID        uuid.UUID
	ProjectID        uuid.UUID
	GatewayAccountID uuid.UUID
	GatewaySessionID string
	PaymentMethod    domain.PaymentMethod
	PayerIp          pgtype.Text
	PayerUserAgent   pgtype.Text
	IdempotencyKey   pgtype.Text
}

func (q *Queries) CreatePaymentSession(ctx context.Context, arg CreatePaymentSessionParams) (PaymentSession, error) {
	row := q.db.QueryRow(ctx, createPaymentSession,
		arg.InvoiceID,
		arg.ProjectID,
		arg.GatewayAccountID,
		arg.GatewaySessionID,
		arg.PaymentMethod,
		arg.PayerIp,
		arg.PayerUserAgent,
		arg.IdempotencyKey,
	)
	var i PaymentSession
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ProjectID,
		&i.GatewayAccountID,
		&i.GatewaySessionID,
		&i.Status,
		&i.PaymentMethod,
		&i.PayerIp,
		&i.PayerUserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getPaymentSessionByIdempotencyKey = `-- name: GetPaymentSessionByIdempotencyKey :one
SELECT id, invoice_id, project_id, gateway_account_id, gateway_session_id, status, payment_method, payer_ip, payer_user_agent, expires_at, created_at, updated_at, deleted_at, idempotency_key FROM payment_sessions
WHERE invoice_id = $1
AND idempotency_key = $2
LIMIT 1
`

type GetPaymentSessionByIdempotencyKeyParams struct {
	InvoiceID      uuid.UUID
	IdempotencyKey pgtype.Text
}

func (q *Queries) GetPaymentSessionByIdempotencyKey(ctx context.Context, arg GetPaymentSessionByIdempotencyKeyParams) (PaymentSession, error) {
	row := q.db.QueryRow(ctx, getPaymentSessionByIdempotencyKey, arg.InvoiceID, arg.IdempotencyKey)
	var i PaymentSession
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ProjectID,
		&i.GatewayAccountID,
		&i.GatewaySessionID,
		&i.Status,
		&i.PaymentMethod,
		&i.PayerIp,
		&i.PayerUserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IdempotencyKey,
	)
	return i, err
}
