// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rbconsult-bh/saftaja/khazina/internal/app/domain"
)

const createProjectForOrganization = `-- name: CreateProjectForOrganization :one
INSERT INTO projects (organization_id, name, environment, custom_domain)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateProjectForOrganizationParams struct {
	OrganizationID uuid.UUID
	Name           string
	Environment    domain.ProjectEnvironment
	CustomDomain   pgtype.Text
}

func (q *Queries) CreateProjectForOrganization(ctx context.Context, arg CreateProjectForOrganizationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createProjectForOrganization,
		arg.OrganizationID,
		arg.Name,
		arg.Environment,
		arg.CustomDomain,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
