// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/rbconsult-bh/saftaja/khazina/internal/domain"
	"github.com/shopspring/decimal"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    payment_intent_id, invoice_id, project_id,
    transaction_type, gateway_transaction_id, amount, currency, raw_request
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, payment_intent_id, invoice_id, project_id, transaction_type, gateway_transaction_id, amount, currency, status, raw_request, raw_response, created_at, updated_at, deleted_at
`

type CreateTransactionParams struct {
	PaymentIntentID      uuid.UUID
	InvoiceID            uuid.UUID
	ProjectID            uuid.UUID
	TransactionType      domain.TransactionType
	GatewayTransactionID string
	Amount               decimal.Decimal
	Currency             string
	RawRequest           []byte
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.PaymentIntentID,
		arg.InvoiceID,
		arg.ProjectID,
		arg.TransactionType,
		arg.GatewayTransactionID,
		arg.Amount,
		arg.Currency,
		arg.RawRequest,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.PaymentIntentID,
		&i.InvoiceID,
		&i.ProjectID,
		&i.TransactionType,
		&i.GatewayTransactionID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.RawRequest,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLatestTransaction = `-- name: GetLatestTransaction :one
SELECT id, payment_intent_id, invoice_id, project_id, transaction_type, gateway_transaction_id, amount, currency, status, raw_request, raw_response, created_at, updated_at, deleted_at FROM transactions
WHERE payment_intent_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestTransaction(ctx context.Context, paymentIntentID uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getLatestTransaction, paymentIntentID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.PaymentIntentID,
		&i.InvoiceID,
		&i.ProjectID,
		&i.TransactionType,
		&i.GatewayTransactionID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.RawRequest,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPayTransactionByPaymentIntentID = `-- name: GetPayTransactionByPaymentIntentID :one
SELECT id, payment_intent_id, invoice_id, project_id, transaction_type, gateway_transaction_id, amount, currency, status, raw_request, raw_response, created_at, updated_at, deleted_at FROM transactions
WHERE payment_intent_id = $1
AND transaction_type = 'pay'
AND status = 'success'
LIMIT 1
`

func (q *Queries) GetPayTransactionByPaymentIntentID(ctx context.Context, paymentIntentID uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getPayTransactionByPaymentIntentID, paymentIntentID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.PaymentIntentID,
		&i.InvoiceID,
		&i.ProjectID,
		&i.TransactionType,
		&i.GatewayTransactionID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.RawRequest,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSuccessfulAuthTransaction = `-- name: GetSuccessfulAuthTransaction :one
SELECT id, payment_intent_id, invoice_id, project_id, transaction_type, gateway_transaction_id, amount, currency, status, raw_request, raw_response, created_at, updated_at, deleted_at FROM transactions
WHERE payment_intent_id = $1
AND transaction_type = 'authenticate_payer'
AND status = 'success'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetSuccessfulAuthTransaction(ctx context.Context, paymentIntentID uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getSuccessfulAuthTransaction, paymentIntentID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.PaymentIntentID,
		&i.InvoiceID,
		&i.ProjectID,
		&i.TransactionType,
		&i.GatewayTransactionID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.RawRequest,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :exec
UPDATE transactions
SET status = $2, raw_response = $3
WHERE id = $1
`

type UpdateTransactionStatusParams struct {
	ID          uuid.UUID
	Status      domain.TransactionStatus
	RawResponse []byte
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) error {
	_, err := q.db.Exec(ctx, updateTransactionStatus, arg.ID, arg.Status, arg.RawResponse)
	return err
}
