// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rbconsult-bh/saftaja/internal/domain"
)

const acceptInvitation = `-- name: AcceptInvitation :exec
UPDATE invitations SET accepted_at = NOW()
WHERE id = $1
`

func (q *Queries) AcceptInvitation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, acceptInvitation, id)
	return err
}

const createAPIKey = `-- name: CreateAPIKey :one

INSERT INTO api_keys (organization_id, project_id, user_id, name, key_hash, key_prefix)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, project_id, user_id, name, key_hash, key_prefix, last_used_at, expires_at, revoked_at, created_at
`

type CreateAPIKeyParams struct {
	OrganizationID uuid.UUID
	ProjectID      uuid.UUID
	UserID         uuid.UUID
	Name           string
	KeyHash        string
	KeyPrefix      string
}

// ============================================================================
// API KEYS
// ============================================================================
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.OrganizationID,
		arg.ProjectID,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one

INSERT INTO invitations (organization_id, email, role, invited_by, token, expires_at)
VALUES ($1, $2, $3, $4, $5, NOW() + INTERVAL '7 days')
RETURNING id, organization_id, email, role, invited_by, token, accepted_at, expires_at, created_at
`

type CreateInvitationParams struct {
	OrganizationID uuid.UUID
	Email          string
	Role           string
	InvitedBy      uuid.UUID
	Token          string
}

// ============================================================================
// INVITATIONS
// ============================================================================
func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.OrganizationID,
		arg.Email,
		arg.Role,
		arg.InvitedBy,
		arg.Token,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.Token,
		&i.AcceptedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOrganizationMember = `-- name: CreateOrganizationMember :one

INSERT INTO organization_members (organization_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, organization_id, user_id, role, created_at
`

type CreateOrganizationMemberParams struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
	Role           string
}

// ============================================================================
// ORGANIZATION MEMBERS
// ============================================================================
func (q *Queries) CreateOrganizationMember(ctx context.Context, arg CreateOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, createOrganizationMember, arg.OrganizationID, arg.UserID, arg.Role)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createOrganizationV1 = `-- name: CreateOrganizationV1 :one

INSERT INTO organizations (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at, deleted_at
`

// ============================================================================
// ORGANIZATIONS (v1 - user scoped)
// ============================================================================
func (q *Queries) CreateOrganizationV1(ctx context.Context, name string) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganizationV1, name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createProjectV1 = `-- name: CreateProjectV1 :one

INSERT INTO projects (organization_id, name, environment, custom_domain, slug)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, name, environment, custom_domain, created_at, updated_at, deleted_at, slug, theme
`

type CreateProjectV1Params struct {
	OrganizationID uuid.UUID
	Name           string
	Environment    domain.ProjectEnvironment
	CustomDomain   pgtype.Text
	Slug           pgtype.Text
}

// ============================================================================
// PROJECTS (v1 - user scoped)
// ============================================================================
func (q *Queries) CreateProjectV1(ctx context.Context, arg CreateProjectV1Params) (Project, error) {
	row := q.db.QueryRow(ctx, createProjectV1,
		arg.OrganizationID,
		arg.Name,
		arg.Environment,
		arg.CustomDomain,
		arg.Slug,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Environment,
		&i.CustomDomain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Slug,
		&i.Theme,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, password_hash, name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, name, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Name         string
}

// ============================================================================
// USERS
// ============================================================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrganizationMember = `-- name: DeleteOrganizationMember :exec
DELETE FROM organization_members
WHERE organization_id = $1 AND user_id = $2
`

type DeleteOrganizationMemberParams struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) DeleteOrganizationMember(ctx context.Context, arg DeleteOrganizationMemberParams) error {
	_, err := q.db.Exec(ctx, deleteOrganizationMember, arg.OrganizationID, arg.UserID)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, organization_id, project_id, user_id, name, key_hash, key_prefix, last_used_at, expires_at, revoked_at, created_at FROM api_keys
WHERE key_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT id, organization_id, email, role, invited_by, token, accepted_at, expires_at, created_at FROM invitations
WHERE token = $1 AND accepted_at IS NULL AND expires_at > NOW()
`

func (q *Queries) GetInvitationByToken(ctx context.Context, token string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByToken, token)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.Token,
		&i.AcceptedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvoiceByIDAndOrgProject = `-- name: GetInvoiceByIDAndOrgProject :one
SELECT i.id, i.project_id, i.amount, i.currency, i.status, i.external_id, i.customer_email, i.customer_name, i.description, i.paid_at, i.created_at, i.updated_at, i.deleted_at FROM invoices i
JOIN projects p ON p.id = i.project_id
JOIN organization_members om ON om.organization_id = p.organization_id
WHERE i.id = $1 AND i.project_id = $2 AND om.user_id = $3 AND i.deleted_at IS NULL
`

type GetInvoiceByIDAndOrgProjectParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) GetInvoiceByIDAndOrgProject(ctx context.Context, arg GetInvoiceByIDAndOrgProjectParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByIDAndOrgProject, arg.ID, arg.ProjectID, arg.UserID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ExternalID,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.Description,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrganizationMember = `-- name: GetOrganizationMember :one
SELECT id, organization_id, user_id, role, created_at FROM organization_members
WHERE organization_id = $1 AND user_id = $2
`

type GetOrganizationMemberParams struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) GetOrganizationMember(ctx context.Context, arg GetOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getOrganizationMember, arg.OrganizationID, arg.UserID)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByIDAndOrg = `-- name: GetProjectByIDAndOrg :one
SELECT id, organization_id, name, environment, custom_domain, created_at, updated_at, deleted_at, slug, theme FROM projects
WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL
`

type GetProjectByIDAndOrgParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetProjectByIDAndOrg(ctx context.Context, arg GetProjectByIDAndOrgParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByIDAndOrg, arg.ID, arg.OrganizationID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Environment,
		&i.CustomDomain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Slug,
		&i.Theme,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, organization_id, project_id, user_id, name, key_hash, key_prefix, last_used_at, expires_at, revoked_at, created_at FROM api_keys
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.UserID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatewayAccountsByProject = `-- name: ListGatewayAccountsByProject :many

SELECT id, project_id, connector_type, account_name, settings, payment_methods, is_active, created_at, updated_at, deleted_at, credentials FROM gateway_accounts
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

// ============================================================================
// GATEWAY ACCOUNTS (v1 - user scoped)
// ============================================================================
func (q *Queries) ListGatewayAccountsByProject(ctx context.Context, projectID uuid.UUID) ([]GatewayAccount, error) {
	rows, err := q.db.Query(ctx, listGatewayAccountsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GatewayAccount
	for rows.Next() {
		var i GatewayAccount
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ConnectorType,
			&i.AccountName,
			&i.Settings,
			&i.PaymentMethods,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Credentials,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByProject = `-- name: ListInvoicesByProject :many

SELECT id, project_id, amount, currency, status, external_id, customer_email, customer_name, description, paid_at, created_at, updated_at, deleted_at FROM invoices
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListInvoicesByProjectParams struct {
	ProjectID uuid.UUID
	Limit     int32
	Offset    int32
}

// ============================================================================
// INVOICES (v1 - user scoped)
// ============================================================================
func (q *Queries) ListInvoicesByProject(ctx context.Context, arg ListInvoicesByProjectParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.ExternalID,
			&i.CustomerEmail,
			&i.CustomerName,
			&i.Description,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationMembers = `-- name: ListOrganizationMembers :many
SELECT om.id, om.organization_id, om.user_id, om.role, om.created_at,
       u.email, u.name AS user_name
FROM organization_members om
JOIN users u ON u.id = om.user_id
WHERE om.organization_id = $1
ORDER BY om.created_at ASC
`

type ListOrganizationMembersRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	UserID         uuid.UUID
	Role           string
	CreatedAt      pgtype.Timestamptz
	Email          string
	UserName       string
}

func (q *Queries) ListOrganizationMembers(ctx context.Context, organizationID uuid.UUID) ([]ListOrganizationMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationMembersRow
	for rows.Next() {
		var i ListOrganizationMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByOrganization = `-- name: ListProjectsByOrganization :many
SELECT id, organization_id, name, environment, custom_domain, created_at, updated_at, deleted_at, slug, theme FROM projects
WHERE organization_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListProjectsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Environment,
			&i.CustomDomain,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Slug,
			&i.Theme,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrganizations = `-- name: ListUserOrganizations :many
SELECT o.id, o.name, o.created_at, o.updated_at, o.deleted_at
FROM organizations o
JOIN organization_members om ON om.organization_id = o.id
WHERE om.user_id = $1 AND o.deleted_at IS NULL
ORDER BY o.created_at ASC
`

func (q *Queries) ListUserOrganizations(ctx context.Context, userID uuid.UUID) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listUserOrganizations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET revoked_at = NOW()
WHERE id = $1 AND user_id = $2
`

type RevokeAPIKeyParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.UserID)
	return err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, id)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $3, custom_domain = $4, slug = $5
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, name, environment, custom_domain, created_at, updated_at, deleted_at, slug, theme
`

type UpdateProjectParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	CustomDomain   pgtype.Text
	Slug           pgtype.Text
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.CustomDomain,
		arg.Slug,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Environment,
		&i.CustomDomain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Slug,
		&i.Theme,
	)
	return i, err
}
