/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardProjectIdRouteImport } from './routes/_dashboard/$projectId'
import { Route as AuthMagicLinkRouteImport } from './routes/_auth/magic-link'
import { Route as AuthAuthRouteImport } from './routes/_auth/auth'
import { Route as DashboardProjectIdSettingsRouteImport } from './routes/_dashboard/$projectId/settings'
import { Route as DashboardProjectIdInvoicesRouteImport } from './routes/_dashboard/$projectId/invoices'
import { Route as DashboardProjectIdGatewaysRouteImport } from './routes/_dashboard/$projectId/gateways'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectIdRoute = DashboardProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthMagicLinkRoute = AuthMagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthRoute = AuthAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardProjectIdSettingsRoute =
  DashboardProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardProjectIdRoute,
  } as any)
const DashboardProjectIdInvoicesRoute =
  DashboardProjectIdInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => DashboardProjectIdRoute,
  } as any)
const DashboardProjectIdGatewaysRoute =
  DashboardProjectIdGatewaysRouteImport.update({
    id: '/gateways',
    path: '/gateways',
    getParentRoute: () => DashboardProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthAuthRoute
  '/magic-link': typeof AuthMagicLinkRoute
  '/$projectId': typeof DashboardProjectIdRouteWithChildren
  '/$projectId/gateways': typeof DashboardProjectIdGatewaysRoute
  '/$projectId/invoices': typeof DashboardProjectIdInvoicesRoute
  '/$projectId/settings': typeof DashboardProjectIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthAuthRoute
  '/magic-link': typeof AuthMagicLinkRoute
  '/$projectId': typeof DashboardProjectIdRouteWithChildren
  '/$projectId/gateways': typeof DashboardProjectIdGatewaysRoute
  '/$projectId/invoices': typeof DashboardProjectIdInvoicesRoute
  '/$projectId/settings': typeof DashboardProjectIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_auth/auth': typeof AuthAuthRoute
  '/_auth/magic-link': typeof AuthMagicLinkRoute
  '/_dashboard/$projectId': typeof DashboardProjectIdRouteWithChildren
  '/_dashboard/$projectId/gateways': typeof DashboardProjectIdGatewaysRoute
  '/_dashboard/$projectId/invoices': typeof DashboardProjectIdInvoicesRoute
  '/_dashboard/$projectId/settings': typeof DashboardProjectIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/magic-link'
    | '/$projectId'
    | '/$projectId/gateways'
    | '/$projectId/invoices'
    | '/$projectId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/magic-link'
    | '/$projectId'
    | '/$projectId/gateways'
    | '/$projectId/invoices'
    | '/$projectId/settings'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/_auth/auth'
    | '/_auth/magic-link'
    | '/_dashboard/$projectId'
    | '/_dashboard/$projectId/gateways'
    | '/_dashboard/$projectId/invoices'
    | '/_dashboard/$projectId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/$projectId': {
      id: '/_dashboard/$projectId'
      path: '/$projectId'
      fullPath: '/$projectId'
      preLoaderRoute: typeof DashboardProjectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/magic-link': {
      id: '/_auth/magic-link'
      path: '/magic-link'
      fullPath: '/magic-link'
      preLoaderRoute: typeof AuthMagicLinkRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/$projectId/settings': {
      id: '/_dashboard/$projectId/settings'
      path: '/settings'
      fullPath: '/$projectId/settings'
      preLoaderRoute: typeof DashboardProjectIdSettingsRouteImport
      parentRoute: typeof DashboardProjectIdRoute
    }
    '/_dashboard/$projectId/invoices': {
      id: '/_dashboard/$projectId/invoices'
      path: '/invoices'
      fullPath: '/$projectId/invoices'
      preLoaderRoute: typeof DashboardProjectIdInvoicesRouteImport
      parentRoute: typeof DashboardProjectIdRoute
    }
    '/_dashboard/$projectId/gateways': {
      id: '/_dashboard/$projectId/gateways'
      path: '/gateways'
      fullPath: '/$projectId/gateways'
      preLoaderRoute: typeof DashboardProjectIdGatewaysRouteImport
      parentRoute: typeof DashboardProjectIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAuthRoute: typeof AuthAuthRoute
  AuthMagicLinkRoute: typeof AuthMagicLinkRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthRoute: AuthAuthRoute,
  AuthMagicLinkRoute: AuthMagicLinkRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardProjectIdRouteChildren {
  DashboardProjectIdGatewaysRoute: typeof DashboardProjectIdGatewaysRoute
  DashboardProjectIdInvoicesRoute: typeof DashboardProjectIdInvoicesRoute
  DashboardProjectIdSettingsRoute: typeof DashboardProjectIdSettingsRoute
}

const DashboardProjectIdRouteChildren: DashboardProjectIdRouteChildren = {
  DashboardProjectIdGatewaysRoute: DashboardProjectIdGatewaysRoute,
  DashboardProjectIdInvoicesRoute: DashboardProjectIdInvoicesRoute,
  DashboardProjectIdSettingsRoute: DashboardProjectIdSettingsRoute,
}

const DashboardProjectIdRouteWithChildren =
  DashboardProjectIdRoute._addFileChildren(DashboardProjectIdRouteChildren)

interface DashboardRouteChildren {
  DashboardProjectIdRoute: typeof DashboardProjectIdRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProjectIdRoute: DashboardProjectIdRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
