// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: saftaja/dashboard/project/v1/project.proto

package projectpbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gateway_ConnectorType int32

const (
	Gateway_CONNECTOR_TYPE_UNSPECIFIED Gateway_ConnectorType = 0
	Gateway_CONNECTOR_TYPE_MPGS        Gateway_ConnectorType = 1
)

// Enum value maps for Gateway_ConnectorType.
var (
	Gateway_ConnectorType_name = map[int32]string{
		0: "CONNECTOR_TYPE_UNSPECIFIED",
		1: "CONNECTOR_TYPE_MPGS",
	}
	Gateway_ConnectorType_value = map[string]int32{
		"CONNECTOR_TYPE_UNSPECIFIED": 0,
		"CONNECTOR_TYPE_MPGS":        1,
	}
)

func (x Gateway_ConnectorType) Enum() *Gateway_ConnectorType {
	p := new(Gateway_ConnectorType)
	*p = x
	return p
}

func (x Gateway_ConnectorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gateway_ConnectorType) Descriptor() protoreflect.EnumDescriptor {
	return file_saftaja_dashboard_project_v1_project_proto_enumTypes[0].Descriptor()
}

func (Gateway_ConnectorType) Type() protoreflect.EnumType {
	return &file_saftaja_dashboard_project_v1_project_proto_enumTypes[0]
}

func (x Gateway_ConnectorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gateway_ConnectorType.Descriptor instead.
func (Gateway_ConnectorType) EnumDescriptor() ([]byte, []int) {
	return file_saftaja_dashboard_project_v1_project_proto_rawDescGZIP(), []int{2, 0}
}

type ListGatewaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGatewaysRequest) Reset() {
	*x = ListGatewaysRequest{}
	mi := &file_saftaja_dashboard_project_v1_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGatewaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGatewaysRequest) ProtoMessage() {}

func (x *ListGatewaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saftaja_dashboard_project_v1_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGatewaysRequest.ProtoReflect.Descriptor instead.
func (*ListGatewaysRequest) Descriptor() ([]byte, []int) {
	return file_saftaja_dashboard_project_v1_project_proto_rawDescGZIP(), []int{0}
}

func (x *ListGatewaysRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListGatewaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gateways      []*Gateway             `protobuf:"bytes,1,rep,name=gateways,proto3" json:"gateways,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGatewaysResponse) Reset() {
	*x = ListGatewaysResponse{}
	mi := &file_saftaja_dashboard_project_v1_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGatewaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGatewaysResponse) ProtoMessage() {}

func (x *ListGatewaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saftaja_dashboard_project_v1_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGatewaysResponse.ProtoReflect.Descriptor instead.
func (*ListGatewaysResponse) Descriptor() ([]byte, []int) {
	return file_saftaja_dashboard_project_v1_project_proto_rawDescGZIP(), []int{1}
}

func (x *ListGatewaysResponse) GetGateways() []*Gateway {
	if x != nil {
		return x.Gateways
	}
	return nil
}

type Gateway struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountName    string                 `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	ConnectorType  Gateway_ConnectorType  `protobuf:"varint,3,opt,name=connector_type,json=connectorType,proto3,enum=saftaja.dashboard.project.v1.Gateway_ConnectorType" json:"connector_type,omitempty"`
	IsActive       bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	PaymentMethods []string               `protobuf:"bytes,5,rep,name=payment_methods,json=paymentMethods,proto3" json:"payment_methods,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Gateway) Reset() {
	*x = Gateway{}
	mi := &file_saftaja_dashboard_project_v1_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gateway) ProtoMessage() {}

func (x *Gateway) ProtoReflect() protoreflect.Message {
	mi := &file_saftaja_dashboard_project_v1_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gateway.ProtoReflect.Descriptor instead.
func (*Gateway) Descriptor() ([]byte, []int) {
	return file_saftaja_dashboard_project_v1_project_proto_rawDescGZIP(), []int{2}
}

func (x *Gateway) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Gateway) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *Gateway) GetConnectorType() Gateway_ConnectorType {
	if x != nil {
		return x.ConnectorType
	}
	return Gateway_CONNECTOR_TYPE_UNSPECIFIED
}

func (x *Gateway) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Gateway) GetPaymentMethods() []string {
	if x != nil {
		return x.PaymentMethods
	}
	return nil
}

type CreateGatewayRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ProjectId   string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	AccountName string                 `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	// Types that are valid to be assigned to Credentials:
	//
	//	*CreateGatewayRequest_Mpgs
	Credentials   isCreateGatewayRequest_Credentials `protobuf_oneof:"credentials"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGatewayRequest) Reset() {
	*x = CreateGatewayRequest{}
	mi := &file_saftaja_dashboard_project_v1_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGatewayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGatewayRequest) ProtoMessage() {}

func (x *CreateGatewayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saftaja_dashboard_project_v1_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGatewayRequest.ProtoReflect.Descriptor instead.
func (*CreateGatewayRequest) Descriptor() ([]byte, []int) {
	return file_saftaja_dashboard_project_v1_project_proto_rawDescGZIP(), []int{3}
}

func (x *CreateGatewayRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateGatewayRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *CreateGatewayRequest) GetCredentials() isCreateGatewayRequest_Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *CreateGatewayRequest) GetMpgs() *MPGSCredentials {
	if x != nil {
		if x, ok := x.Credentials.(*CreateGatewayRequest_Mpgs); ok {
			return x.Mpgs
		}
	}
	return nil
}

type isCreateGatewayRequest_Credentials interface {
	isCreateGatewayRequest_Credentials()
}

type CreateGatewayRequest_Mpgs struct {
	Mpgs *MPGSCredentials `protobuf:"bytes,3,opt,name=mpgs,proto3,oneof"`
}

func (*CreateGatewayRequest_Mpgs) isCreateGatewayRequest_Credentials() {}

type CreateGatewayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGatewayResponse) Reset() {
	*x = CreateGatewayResponse{}
	mi := &file_saftaja_dashboard_project_v1_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGatewayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGatewayResponse) ProtoMessage() {}

func (x *CreateGatewayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saftaja_dashboard_project_v1_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGatewayResponse.ProtoReflect.Descriptor instead.
func (*CreateGatewayResponse) Descriptor() ([]byte, []int) {
	return file_saftaja_dashboard_project_v1_project_proto_rawDescGZIP(), []int{4}
}

type MPGSCredentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ApiPassword   string                 `protobuf:"bytes,3,opt,name=api_password,json=apiPassword,proto3" json:"api_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MPGSCredentials) Reset() {
	*x = MPGSCredentials{}
	mi := &file_saftaja_dashboard_project_v1_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MPGSCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPGSCredentials) ProtoMessage() {}

func (x *MPGSCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_saftaja_dashboard_project_v1_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPGSCredentials.ProtoReflect.Descriptor instead.
func (*MPGSCredentials) Descriptor() ([]byte, []int) {
	return file_saftaja_dashboard_project_v1_project_proto_rawDescGZIP(), []int{5}
}

func (x *MPGSCredentials) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *MPGSCredentials) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *MPGSCredentials) GetApiPassword() string {
	if x != nil {
		return x.ApiPassword
	}
	return ""
}

var File_saftaja_dashboard_project_v1_project_proto protoreflect.FileDescriptor

const file_saftaja_dashboard_project_v1_project_proto_rawDesc = "" +
	"\n" +
	"*saftaja/dashboard/project/v1/project.proto\x12\x1csaftaja.dashboard.project.v1\"4\n" +
	"\x13ListGatewaysRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"Y\n" +
	"\x14ListGatewaysResponse\x12A\n" +
	"\bgateways\x18\x01 \x03(\v2%.saftaja.dashboard.project.v1.GatewayR\bgateways\"\xa8\x02\n" +
	"\aGateway\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\faccount_name\x18\x02 \x01(\tR\vaccountName\x12Z\n" +
	"\x0econnector_type\x18\x03 \x01(\x0e23.saftaja.dashboard.project.v1.Gateway.ConnectorTypeR\rconnectorType\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12'\n" +
	"\x0fpayment_methods\x18\x05 \x03(\tR\x0epaymentMethods\"H\n" +
	"\rConnectorType\x12\x1e\n" +
	"\x1aCONNECTOR_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CONNECTOR_TYPE_MPGS\x10\x01\"\xac\x01\n" +
	"\x14CreateGatewayRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12!\n" +
	"\faccount_name\x18\x02 \x01(\tR\vaccountName\x12C\n" +
	"\x04mpgs\x18\x03 \x01(\v2-.saftaja.dashboard.project.v1.MPGSCredentialsH\x00R\x04mpgsB\r\n" +
	"\vcredentials\"\x17\n" +
	"\x15CreateGatewayResponse\"p\n" +
	"\x0fMPGSCredentials\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12!\n" +
	"\fapi_password\x18\x03 \x01(\tR\vapiPassword2\x81\x02\n" +
	"\x0eProjectService\x12u\n" +
	"\fListGateways\x121.saftaja.dashboard.project.v1.ListGatewaysRequest\x1a2.saftaja.dashboard.project.v1.ListGatewaysResponse\x12x\n" +
	"\rCreateGateway\x122.saftaja.dashboard.project.v1.CreateGatewayRequest\x1a3.saftaja.dashboard.project.v1.CreateGatewayResponseBkZigithub.com/rbconsult-bh/saftaja/khazina/internal/transport/proto/saftaja/dashboard/project/v1;projectpbv1b\x06proto3"

var (
	file_saftaja_dashboard_project_v1_project_proto_rawDescOnce sync.Once
	file_saftaja_dashboard_project_v1_project_proto_rawDescData []byte
)

func file_saftaja_dashboard_project_v1_project_proto_rawDescGZIP() []byte {
	file_saftaja_dashboard_project_v1_project_proto_rawDescOnce.Do(func() {
		file_saftaja_dashboard_project_v1_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_saftaja_dashboard_project_v1_project_proto_rawDesc), len(file_saftaja_dashboard_project_v1_project_proto_rawDesc)))
	})
	return file_saftaja_dashboard_project_v1_project_proto_rawDescData
}

var file_saftaja_dashboard_project_v1_project_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_saftaja_dashboard_project_v1_project_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_saftaja_dashboard_project_v1_project_proto_goTypes = []any{
	(Gateway_ConnectorType)(0),    // 0: saftaja.dashboard.project.v1.Gateway.ConnectorType
	(*ListGatewaysRequest)(nil),   // 1: saftaja.dashboard.project.v1.ListGatewaysRequest
	(*ListGatewaysResponse)(nil),  // 2: saftaja.dashboard.project.v1.ListGatewaysResponse
	(*Gateway)(nil),               // 3: saftaja.dashboard.project.v1.Gateway
	(*CreateGatewayRequest)(nil),  // 4: saftaja.dashboard.project.v1.CreateGatewayRequest
	(*CreateGatewayResponse)(nil), // 5: saftaja.dashboard.project.v1.CreateGatewayResponse
	(*MPGSCredentials)(nil),       // 6: saftaja.dashboard.project.v1.MPGSCredentials
}
var file_saftaja_dashboard_project_v1_project_proto_depIdxs = []int32{
	3, // 0: saftaja.dashboard.project.v1.ListGatewaysResponse.gateways:type_name -> saftaja.dashboard.project.v1.Gateway
	0, // 1: saftaja.dashboard.project.v1.Gateway.connector_type:type_name -> saftaja.dashboard.project.v1.Gateway.ConnectorType
	6, // 2: saftaja.dashboard.project.v1.CreateGatewayRequest.mpgs:type_name -> saftaja.dashboard.project.v1.MPGSCredentials
	1, // 3: saftaja.dashboard.project.v1.ProjectService.ListGateways:input_type -> saftaja.dashboard.project.v1.ListGatewaysRequest
	4, // 4: saftaja.dashboard.project.v1.ProjectService.CreateGateway:input_type -> saftaja.dashboard.project.v1.CreateGatewayRequest
	2, // 5: saftaja.dashboard.project.v1.ProjectService.ListGateways:output_type -> saftaja.dashboard.project.v1.ListGatewaysResponse
	5, // 6: saftaja.dashboard.project.v1.ProjectService.CreateGateway:output_type -> saftaja.dashboard.project.v1.CreateGatewayResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_saftaja_dashboard_project_v1_project_proto_init() }
func file_saftaja_dashboard_project_v1_project_proto_init() {
	if File_saftaja_dashboard_project_v1_project_proto != nil {
		return
	}
	file_saftaja_dashboard_project_v1_project_proto_msgTypes[3].OneofWrappers = []any{
		(*CreateGatewayRequest_Mpgs)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_saftaja_dashboard_project_v1_project_proto_rawDesc), len(file_saftaja_dashboard_project_v1_project_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_saftaja_dashboard_project_v1_project_proto_goTypes,
		DependencyIndexes: file_saftaja_dashboard_project_v1_project_proto_depIdxs,
		EnumInfos:         file_saftaja_dashboard_project_v1_project_proto_enumTypes,
		MessageInfos:      file_saftaja_dashboard_project_v1_project_proto_msgTypes,
	}.Build()
	File_saftaja_dashboard_project_v1_project_proto = out.File
	file_saftaja_dashboard_project_v1_project_proto_goTypes = nil
	file_saftaja_dashboard_project_v1_project_proto_depIdxs = nil
}
