// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rbconsult-bh/saftaja/khazina/internal/app/billing"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CapturePayment provides a mock function for the type MockService
func (_mock *MockService) CapturePayment(ctx context.Context, r billing.CapturePaymentRequest) (*billing.CapturePaymentResponse, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for CapturePayment")
	}

	var r0 *billing.CapturePaymentResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.CapturePaymentRequest) (*billing.CapturePaymentResponse, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.CapturePaymentRequest) *billing.CapturePaymentResponse); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.CapturePaymentResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, billing.CapturePaymentRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CapturePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CapturePayment'
type MockService_CapturePayment_Call struct {
	*mock.Call
}

// CapturePayment is a helper method to define mock.On call
//   - ctx context.Context
//   - r billing.CapturePaymentRequest
func (_e *MockService_Expecter) CapturePayment(ctx interface{}, r interface{}) *MockService_CapturePayment_Call {
	return &MockService_CapturePayment_Call{Call: _e.mock.On("CapturePayment", ctx, r)}
}

func (_c *MockService_CapturePayment_Call) Run(run func(ctx context.Context, r billing.CapturePaymentRequest)) *MockService_CapturePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 billing.CapturePaymentRequest
		if args[1] != nil {
			arg1 = args[1].(billing.CapturePaymentRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CapturePayment_Call) Return(capturePaymentResponse *billing.CapturePaymentResponse, err error) *MockService_CapturePayment_Call {
	_c.Call.Return(capturePaymentResponse, err)
	return _c
}

func (_c *MockService_CapturePayment_Call) RunAndReturn(run func(ctx context.Context, r billing.CapturePaymentRequest) (*billing.CapturePaymentResponse, error)) *MockService_CapturePayment_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteCardChallenge provides a mock function for the type MockService
func (_mock *MockService) CompleteCardChallenge(ctx context.Context, r billing.CompleteCardChallengeRequest) (*billing.CompleteCardChallengeResponse, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for CompleteCardChallenge")
	}

	var r0 *billing.CompleteCardChallengeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.CompleteCardChallengeRequest) (*billing.CompleteCardChallengeResponse, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.CompleteCardChallengeRequest) *billing.CompleteCardChallengeResponse); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.CompleteCardChallengeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, billing.CompleteCardChallengeRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CompleteCardChallenge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteCardChallenge'
type MockService_CompleteCardChallenge_Call struct {
	*mock.Call
}

// CompleteCardChallenge is a helper method to define mock.On call
//   - ctx context.Context
//   - r billing.CompleteCardChallengeRequest
func (_e *MockService_Expecter) CompleteCardChallenge(ctx interface{}, r interface{}) *MockService_CompleteCardChallenge_Call {
	return &MockService_CompleteCardChallenge_Call{Call: _e.mock.On("CompleteCardChallenge", ctx, r)}
}

func (_c *MockService_CompleteCardChallenge_Call) Run(run func(ctx context.Context, r billing.CompleteCardChallengeRequest)) *MockService_CompleteCardChallenge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 billing.CompleteCardChallengeRequest
		if args[1] != nil {
			arg1 = args[1].(billing.CompleteCardChallengeRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CompleteCardChallenge_Call) Return(completeCardChallengeResponse *billing.CompleteCardChallengeResponse, err error) *MockService_CompleteCardChallenge_Call {
	_c.Call.Return(completeCardChallengeResponse, err)
	return _c
}

func (_c *MockService_CompleteCardChallenge_Call) RunAndReturn(run func(ctx context.Context, r billing.CompleteCardChallengeRequest) (*billing.CompleteCardChallengeResponse, error)) *MockService_CompleteCardChallenge_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvoice provides a mock function for the type MockService
func (_mock *MockService) GetInvoice(ctx context.Context, r billing.GetInvoiceRequest) (*billing.GetInvoiceResponse, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for GetInvoice")
	}

	var r0 *billing.GetInvoiceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.GetInvoiceRequest) (*billing.GetInvoiceResponse, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.GetInvoiceRequest) *billing.GetInvoiceResponse); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.GetInvoiceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, billing.GetInvoiceRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvoice'
type MockService_GetInvoice_Call struct {
	*mock.Call
}

// GetInvoice is a helper method to define mock.On call
//   - ctx context.Context
//   - r billing.GetInvoiceRequest
func (_e *MockService_Expecter) GetInvoice(ctx interface{}, r interface{}) *MockService_GetInvoice_Call {
	return &MockService_GetInvoice_Call{Call: _e.mock.On("GetInvoice", ctx, r)}
}

func (_c *MockService_GetInvoice_Call) Run(run func(ctx context.Context, r billing.GetInvoiceRequest)) *MockService_GetInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 billing.GetInvoiceRequest
		if args[1] != nil {
			arg1 = args[1].(billing.GetInvoiceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetInvoice_Call) Return(getInvoiceResponse *billing.GetInvoiceResponse, err error) *MockService_GetInvoice_Call {
	_c.Call.Return(getInvoiceResponse, err)
	return _c
}

func (_c *MockService_GetInvoice_Call) RunAndReturn(run func(ctx context.Context, r billing.GetInvoiceRequest) (*billing.GetInvoiceResponse, error)) *MockService_GetInvoice_Call {
	_c.Call.Return(run)
	return _c
}

// StartCardChallenge provides a mock function for the type MockService
func (_mock *MockService) StartCardChallenge(ctx context.Context, r billing.StartCardChallengeRequest) (*billing.StartCardChallengeResponse, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for StartCardChallenge")
	}

	var r0 *billing.StartCardChallengeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.StartCardChallengeRequest) (*billing.StartCardChallengeResponse, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.StartCardChallengeRequest) *billing.StartCardChallengeResponse); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.StartCardChallengeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, billing.StartCardChallengeRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_StartCardChallenge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartCardChallenge'
type MockService_StartCardChallenge_Call struct {
	*mock.Call
}

// StartCardChallenge is a helper method to define mock.On call
//   - ctx context.Context
//   - r billing.StartCardChallengeRequest
func (_e *MockService_Expecter) StartCardChallenge(ctx interface{}, r interface{}) *MockService_StartCardChallenge_Call {
	return &MockService_StartCardChallenge_Call{Call: _e.mock.On("StartCardChallenge", ctx, r)}
}

func (_c *MockService_StartCardChallenge_Call) Run(run func(ctx context.Context, r billing.StartCardChallengeRequest)) *MockService_StartCardChallenge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 billing.StartCardChallengeRequest
		if args[1] != nil {
			arg1 = args[1].(billing.StartCardChallengeRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_StartCardChallenge_Call) Return(startCardChallengeResponse *billing.StartCardChallengeResponse, err error) *MockService_StartCardChallenge_Call {
	_c.Call.Return(startCardChallengeResponse, err)
	return _c
}

func (_c *MockService_StartCardChallenge_Call) RunAndReturn(run func(ctx context.Context, r billing.StartCardChallengeRequest) (*billing.StartCardChallengeResponse, error)) *MockService_StartCardChallenge_Call {
	_c.Call.Return(run)
	return _c
}

// StartPayment provides a mock function for the type MockService
func (_mock *MockService) StartPayment(ctx context.Context, r billing.StartPaymentRequest) (*billing.StartPaymentResponse, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for StartPayment")
	}

	var r0 *billing.StartPaymentResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.StartPaymentRequest) (*billing.StartPaymentResponse, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.StartPaymentRequest) *billing.StartPaymentResponse); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.StartPaymentResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, billing.StartPaymentRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_StartPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartPayment'
type MockService_StartPayment_Call struct {
	*mock.Call
}

// StartPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - r billing.StartPaymentRequest
func (_e *MockService_Expecter) StartPayment(ctx interface{}, r interface{}) *MockService_StartPayment_Call {
	return &MockService_StartPayment_Call{Call: _e.mock.On("StartPayment", ctx, r)}
}

func (_c *MockService_StartPayment_Call) Run(run func(ctx context.Context, r billing.StartPaymentRequest)) *MockService_StartPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 billing.StartPaymentRequest
		if args[1] != nil {
			arg1 = args[1].(billing.StartPaymentRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_StartPayment_Call) Return(startPaymentResponse *billing.StartPaymentResponse, err error) *MockService_StartPayment_Call {
	_c.Call.Return(startPaymentResponse, err)
	return _c
}

func (_c *MockService_StartPayment_Call) RunAndReturn(run func(ctx context.Context, r billing.StartPaymentRequest) (*billing.StartPaymentResponse, error)) *MockService_StartPayment_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyCard provides a mock function for the type MockService
func (_mock *MockService) VerifyCard(ctx context.Context, r billing.VerifyCardRequest) (*billing.VerifyCardResponse, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for VerifyCard")
	}

	var r0 *billing.VerifyCardResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.VerifyCardRequest) (*billing.VerifyCardResponse, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.VerifyCardRequest) *billing.VerifyCardResponse); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.VerifyCardResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, billing.VerifyCardRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_VerifyCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyCard'
type MockService_VerifyCard_Call struct {
	*mock.Call
}

// VerifyCard is a helper method to define mock.On call
//   - ctx context.Context
//   - r billing.VerifyCardRequest
func (_e *MockService_Expecter) VerifyCard(ctx interface{}, r interface{}) *MockService_VerifyCard_Call {
	return &MockService_VerifyCard_Call{Call: _e.mock.On("VerifyCard", ctx, r)}
}

func (_c *MockService_VerifyCard_Call) Run(run func(ctx context.Context, r billing.VerifyCardRequest)) *MockService_VerifyCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 billing.VerifyCardRequest
		if args[1] != nil {
			arg1 = args[1].(billing.VerifyCardRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_VerifyCard_Call) Return(verifyCardResponse *billing.VerifyCardResponse, err error) *MockService_VerifyCard_Call {
	_c.Call.Return(verifyCardResponse, err)
	return _c
}

func (_c *MockService_VerifyCard_Call) RunAndReturn(run func(ctx context.Context, r billing.VerifyCardRequest) (*billing.VerifyCardResponse, error)) *MockService_VerifyCard_Call {
	_c.Call.Return(run)
	return _c
}
