// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rbconsult-bh/saftaja/khazina/internal/app/billing"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AuthenticateCardholder provides a mock function for the type MockService
func (_mock *MockService) AuthenticateCardholder(ctx context.Context, r billing.AuthenticateCardholderRequest) (*billing.AuthenticateCardholderResponse, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateCardholder")
	}

	var r0 *billing.AuthenticateCardholderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.AuthenticateCardholderRequest) (*billing.AuthenticateCardholderResponse, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.AuthenticateCardholderRequest) *billing.AuthenticateCardholderResponse); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.AuthenticateCardholderResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, billing.AuthenticateCardholderRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_AuthenticateCardholder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateCardholder'
type MockService_AuthenticateCardholder_Call struct {
	*mock.Call
}

// AuthenticateCardholder is a helper method to define mock.On call
//   - ctx context.Context
//   - r billing.AuthenticateCardholderRequest
func (_e *MockService_Expecter) AuthenticateCardholder(ctx interface{}, r interface{}) *MockService_AuthenticateCardholder_Call {
	return &MockService_AuthenticateCardholder_Call{Call: _e.mock.On("AuthenticateCardholder", ctx, r)}
}

func (_c *MockService_AuthenticateCardholder_Call) Run(run func(ctx context.Context, r billing.AuthenticateCardholderRequest)) *MockService_AuthenticateCardholder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 billing.AuthenticateCardholderRequest
		if args[1] != nil {
			arg1 = args[1].(billing.AuthenticateCardholderRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_AuthenticateCardholder_Call) Return(authenticateCardholderResponse *billing.AuthenticateCardholderResponse, err error) *MockService_AuthenticateCardholder_Call {
	_c.Call.Return(authenticateCardholderResponse, err)
	return _c
}

func (_c *MockService_AuthenticateCardholder_Call) RunAndReturn(run func(ctx context.Context, r billing.AuthenticateCardholderRequest) (*billing.AuthenticateCardholderResponse, error)) *MockService_AuthenticateCardholder_Call {
	_c.Call.Return(run)
	return _c
}

// CapturePaymentIntent provides a mock function for the type MockService
func (_mock *MockService) CapturePaymentIntent(ctx context.Context, r billing.CapturePaymentIntentRequest) (*billing.CapturePaymentIntentResponse, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for CapturePaymentIntent")
	}

	var r0 *billing.CapturePaymentIntentResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.CapturePaymentIntentRequest) (*billing.CapturePaymentIntentResponse, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.CapturePaymentIntentRequest) *billing.CapturePaymentIntentResponse); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.CapturePaymentIntentResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, billing.CapturePaymentIntentRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CapturePaymentIntent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CapturePaymentIntent'
type MockService_CapturePaymentIntent_Call struct {
	*mock.Call
}

// CapturePaymentIntent is a helper method to define mock.On call
//   - ctx context.Context
//   - r billing.CapturePaymentIntentRequest
func (_e *MockService_Expecter) CapturePaymentIntent(ctx interface{}, r interface{}) *MockService_CapturePaymentIntent_Call {
	return &MockService_CapturePaymentIntent_Call{Call: _e.mock.On("CapturePaymentIntent", ctx, r)}
}

func (_c *MockService_CapturePaymentIntent_Call) Run(run func(ctx context.Context, r billing.CapturePaymentIntentRequest)) *MockService_CapturePaymentIntent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 billing.CapturePaymentIntentRequest
		if args[1] != nil {
			arg1 = args[1].(billing.CapturePaymentIntentRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CapturePaymentIntent_Call) Return(capturePaymentIntentResponse *billing.CapturePaymentIntentResponse, err error) *MockService_CapturePaymentIntent_Call {
	_c.Call.Return(capturePaymentIntentResponse, err)
	return _c
}

func (_c *MockService_CapturePaymentIntent_Call) RunAndReturn(run func(ctx context.Context, r billing.CapturePaymentIntentRequest) (*billing.CapturePaymentIntentResponse, error)) *MockService_CapturePaymentIntent_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePaymentIntent provides a mock function for the type MockService
func (_mock *MockService) CreatePaymentIntent(ctx context.Context, r billing.CreatePaymentIntentRequest) (*billing.CreatePaymentIntentResponse, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for CreatePaymentIntent")
	}

	var r0 *billing.CreatePaymentIntentResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.CreatePaymentIntentRequest) (*billing.CreatePaymentIntentResponse, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.CreatePaymentIntentRequest) *billing.CreatePaymentIntentResponse); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.CreatePaymentIntentResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, billing.CreatePaymentIntentRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreatePaymentIntent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePaymentIntent'
type MockService_CreatePaymentIntent_Call struct {
	*mock.Call
}

// CreatePaymentIntent is a helper method to define mock.On call
//   - ctx context.Context
//   - r billing.CreatePaymentIntentRequest
func (_e *MockService_Expecter) CreatePaymentIntent(ctx interface{}, r interface{}) *MockService_CreatePaymentIntent_Call {
	return &MockService_CreatePaymentIntent_Call{Call: _e.mock.On("CreatePaymentIntent", ctx, r)}
}

func (_c *MockService_CreatePaymentIntent_Call) Run(run func(ctx context.Context, r billing.CreatePaymentIntentRequest)) *MockService_CreatePaymentIntent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 billing.CreatePaymentIntentRequest
		if args[1] != nil {
			arg1 = args[1].(billing.CreatePaymentIntentRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CreatePaymentIntent_Call) Return(createPaymentIntentResponse *billing.CreatePaymentIntentResponse, err error) *MockService_CreatePaymentIntent_Call {
	_c.Call.Return(createPaymentIntentResponse, err)
	return _c
}

func (_c *MockService_CreatePaymentIntent_Call) RunAndReturn(run func(ctx context.Context, r billing.CreatePaymentIntentRequest) (*billing.CreatePaymentIntentResponse, error)) *MockService_CreatePaymentIntent_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvoice provides a mock function for the type MockService
func (_mock *MockService) GetInvoice(ctx context.Context, r billing.GetInvoiceRequest) (*billing.GetInvoiceResponse, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for GetInvoice")
	}

	var r0 *billing.GetInvoiceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.GetInvoiceRequest) (*billing.GetInvoiceResponse, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.GetInvoiceRequest) *billing.GetInvoiceResponse); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.GetInvoiceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, billing.GetInvoiceRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvoice'
type MockService_GetInvoice_Call struct {
	*mock.Call
}

// GetInvoice is a helper method to define mock.On call
//   - ctx context.Context
//   - r billing.GetInvoiceRequest
func (_e *MockService_Expecter) GetInvoice(ctx interface{}, r interface{}) *MockService_GetInvoice_Call {
	return &MockService_GetInvoice_Call{Call: _e.mock.On("GetInvoice", ctx, r)}
}

func (_c *MockService_GetInvoice_Call) Run(run func(ctx context.Context, r billing.GetInvoiceRequest)) *MockService_GetInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 billing.GetInvoiceRequest
		if args[1] != nil {
			arg1 = args[1].(billing.GetInvoiceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetInvoice_Call) Return(getInvoiceResponse *billing.GetInvoiceResponse, err error) *MockService_GetInvoice_Call {
	_c.Call.Return(getInvoiceResponse, err)
	return _c
}

func (_c *MockService_GetInvoice_Call) RunAndReturn(run func(ctx context.Context, r billing.GetInvoiceRequest) (*billing.GetInvoiceResponse, error)) *MockService_GetInvoice_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareCardAuthentication provides a mock function for the type MockService
func (_mock *MockService) PrepareCardAuthentication(ctx context.Context, r billing.PrepareCardAuthenticationRequest) (*billing.PrepareCardAuthenticationResponse, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for PrepareCardAuthentication")
	}

	var r0 *billing.PrepareCardAuthenticationResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.PrepareCardAuthenticationRequest) (*billing.PrepareCardAuthenticationResponse, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.PrepareCardAuthenticationRequest) *billing.PrepareCardAuthenticationResponse); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.PrepareCardAuthenticationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, billing.PrepareCardAuthenticationRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_PrepareCardAuthentication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareCardAuthentication'
type MockService_PrepareCardAuthentication_Call struct {
	*mock.Call
}

// PrepareCardAuthentication is a helper method to define mock.On call
//   - ctx context.Context
//   - r billing.PrepareCardAuthenticationRequest
func (_e *MockService_Expecter) PrepareCardAuthentication(ctx interface{}, r interface{}) *MockService_PrepareCardAuthentication_Call {
	return &MockService_PrepareCardAuthentication_Call{Call: _e.mock.On("PrepareCardAuthentication", ctx, r)}
}

func (_c *MockService_PrepareCardAuthentication_Call) Run(run func(ctx context.Context, r billing.PrepareCardAuthenticationRequest)) *MockService_PrepareCardAuthentication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 billing.PrepareCardAuthenticationRequest
		if args[1] != nil {
			arg1 = args[1].(billing.PrepareCardAuthenticationRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_PrepareCardAuthentication_Call) Return(prepareCardAuthenticationResponse *billing.PrepareCardAuthenticationResponse, err error) *MockService_PrepareCardAuthentication_Call {
	_c.Call.Return(prepareCardAuthenticationResponse, err)
	return _c
}

func (_c *MockService_PrepareCardAuthentication_Call) RunAndReturn(run func(ctx context.Context, r billing.PrepareCardAuthenticationRequest) (*billing.PrepareCardAuthenticationResponse, error)) *MockService_PrepareCardAuthentication_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyCardAuthentication provides a mock function for the type MockService
func (_mock *MockService) VerifyCardAuthentication(ctx context.Context, r billing.VerifyCardAuthenticationRequest) (*billing.VerifyCardAuthenticationResponse, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for VerifyCardAuthentication")
	}

	var r0 *billing.VerifyCardAuthenticationResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.VerifyCardAuthenticationRequest) (*billing.VerifyCardAuthenticationResponse, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing.VerifyCardAuthenticationRequest) *billing.VerifyCardAuthenticationResponse); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.VerifyCardAuthenticationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, billing.VerifyCardAuthenticationRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_VerifyCardAuthentication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyCardAuthentication'
type MockService_VerifyCardAuthentication_Call struct {
	*mock.Call
}

// VerifyCardAuthentication is a helper method to define mock.On call
//   - ctx context.Context
//   - r billing.VerifyCardAuthenticationRequest
func (_e *MockService_Expecter) VerifyCardAuthentication(ctx interface{}, r interface{}) *MockService_VerifyCardAuthentication_Call {
	return &MockService_VerifyCardAuthentication_Call{Call: _e.mock.On("VerifyCardAuthentication", ctx, r)}
}

func (_c *MockService_VerifyCardAuthentication_Call) Run(run func(ctx context.Context, r billing.VerifyCardAuthenticationRequest)) *MockService_VerifyCardAuthentication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 billing.VerifyCardAuthenticationRequest
		if args[1] != nil {
			arg1 = args[1].(billing.VerifyCardAuthenticationRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_VerifyCardAuthentication_Call) Return(verifyCardAuthenticationResponse *billing.VerifyCardAuthenticationResponse, err error) *MockService_VerifyCardAuthentication_Call {
	_c.Call.Return(verifyCardAuthenticationResponse, err)
	return _c
}

func (_c *MockService_VerifyCardAuthentication_Call) RunAndReturn(run func(ctx context.Context, r billing.VerifyCardAuthenticationRequest) (*billing.VerifyCardAuthenticationResponse, error)) *MockService_VerifyCardAuthentication_Call {
	_c.Call.Return(run)
	return _c
}
