// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	payment "github.com/rbconsult-bh/saftaja/internal/payment"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// FinalizePayment provides a mock function with given fields: ctx, req
func (_m *MockService) FinalizePayment(ctx context.Context, req *payment.FinalizePaymentRequest) (*payment.FinalizePaymentResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for FinalizePayment")
	}

	var r0 *payment.FinalizePaymentResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *payment.FinalizePaymentRequest) (*payment.FinalizePaymentResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *payment.FinalizePaymentRequest) *payment.FinalizePaymentResult); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.FinalizePaymentResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *payment.FinalizePaymentRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_FinalizePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinalizePayment'
type MockService_FinalizePayment_Call struct {
	*mock.Call
}

// FinalizePayment is a helper method to define mock.On call
//   - ctx context.Context
//   - req *payment.FinalizePaymentRequest
func (_e *MockService_Expecter) FinalizePayment(ctx interface{}, req interface{}) *MockService_FinalizePayment_Call {
	return &MockService_FinalizePayment_Call{Call: _e.mock.On("FinalizePayment", ctx, req)}
}

func (_c *MockService_FinalizePayment_Call) Run(run func(ctx context.Context, req *payment.FinalizePaymentRequest)) *MockService_FinalizePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*payment.FinalizePaymentRequest))
	})
	return _c
}

func (_c *MockService_FinalizePayment_Call) Return(_a0 *payment.FinalizePaymentResult, _a1 error) *MockService_FinalizePayment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_FinalizePayment_Call) RunAndReturn(run func(context.Context, *payment.FinalizePaymentRequest) (*payment.FinalizePaymentResult, error)) *MockService_FinalizePayment_Call {
	_c.Call.Return(run)
	return _c
}

// GetCheckoutData provides a mock function with given fields: ctx, invoiceID, projectID
func (_m *MockService) GetCheckoutData(ctx context.Context, invoiceID uuid.UUID, projectID uuid.UUID) (*payment.CheckoutData, error) {
	ret := _m.Called(ctx, invoiceID, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetCheckoutData")
	}

	var r0 *payment.CheckoutData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*payment.CheckoutData, error)); ok {
		return rf(ctx, invoiceID, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *payment.CheckoutData); ok {
		r0 = rf(ctx, invoiceID, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.CheckoutData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, invoiceID, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetCheckoutData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCheckoutData'
type MockService_GetCheckoutData_Call struct {
	*mock.Call
}

// GetCheckoutData is a helper method to define mock.On call
//   - ctx context.Context
//   - invoiceID uuid.UUID
//   - projectID uuid.UUID
func (_e *MockService_Expecter) GetCheckoutData(ctx interface{}, invoiceID interface{}, projectID interface{}) *MockService_GetCheckoutData_Call {
	return &MockService_GetCheckoutData_Call{Call: _e.mock.On("GetCheckoutData", ctx, invoiceID, projectID)}
}

func (_c *MockService_GetCheckoutData_Call) Run(run func(ctx context.Context, invoiceID uuid.UUID, projectID uuid.UUID)) *MockService_GetCheckoutData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_GetCheckoutData_Call) Return(_a0 *payment.CheckoutData, _a1 error) *MockService_GetCheckoutData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetCheckoutData_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*payment.CheckoutData, error)) *MockService_GetCheckoutData_Call {
	_c.Call.Return(run)
	return _c
}

// InitiateAuth provides a mock function with given fields: ctx, req
func (_m *MockService) InitiateAuth(ctx context.Context, req *payment.InitiateAuthRequest) (*payment.InitiateAuthResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for InitiateAuth")
	}

	var r0 *payment.InitiateAuthResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *payment.InitiateAuthRequest) (*payment.InitiateAuthResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *payment.InitiateAuthRequest) *payment.InitiateAuthResult); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.InitiateAuthResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *payment.InitiateAuthRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_InitiateAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitiateAuth'
type MockService_InitiateAuth_Call struct {
	*mock.Call
}

// InitiateAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - req *payment.InitiateAuthRequest
func (_e *MockService_Expecter) InitiateAuth(ctx interface{}, req interface{}) *MockService_InitiateAuth_Call {
	return &MockService_InitiateAuth_Call{Call: _e.mock.On("InitiateAuth", ctx, req)}
}

func (_c *MockService_InitiateAuth_Call) Run(run func(ctx context.Context, req *payment.InitiateAuthRequest)) *MockService_InitiateAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*payment.InitiateAuthRequest))
	})
	return _c
}

func (_c *MockService_InitiateAuth_Call) Return(_a0 *payment.InitiateAuthResult, _a1 error) *MockService_InitiateAuth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_InitiateAuth_Call) RunAndReturn(run func(context.Context, *payment.InitiateAuthRequest) (*payment.InitiateAuthResult, error)) *MockService_InitiateAuth_Call {
	_c.Call.Return(run)
	return _c
}

// InitiateSession provides a mock function with given fields: ctx, req
func (_m *MockService) InitiateSession(ctx context.Context, req *payment.InitiateSessionRequest) (*payment.InitiateSessionResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for InitiateSession")
	}

	var r0 *payment.InitiateSessionResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *payment.InitiateSessionRequest) (*payment.InitiateSessionResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *payment.InitiateSessionRequest) *payment.InitiateSessionResult); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.InitiateSessionResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *payment.InitiateSessionRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_InitiateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitiateSession'
type MockService_InitiateSession_Call struct {
	*mock.Call
}

// InitiateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - req *payment.InitiateSessionRequest
func (_e *MockService_Expecter) InitiateSession(ctx interface{}, req interface{}) *MockService_InitiateSession_Call {
	return &MockService_InitiateSession_Call{Call: _e.mock.On("InitiateSession", ctx, req)}
}

func (_c *MockService_InitiateSession_Call) Run(run func(ctx context.Context, req *payment.InitiateSessionRequest)) *MockService_InitiateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*payment.InitiateSessionRequest))
	})
	return _c
}

func (_c *MockService_InitiateSession_Call) Return(_a0 *payment.InitiateSessionResult, _a1 error) *MockService_InitiateSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_InitiateSession_Call) RunAndReturn(run func(context.Context, *payment.InitiateSessionRequest) (*payment.InitiateSessionResult, error)) *MockService_InitiateSession_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessAuth provides a mock function with given fields: ctx, req
func (_m *MockService) ProcessAuth(ctx context.Context, req *payment.ProcessAuthRequest) (*payment.ProcessAuthResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ProcessAuth")
	}

	var r0 *payment.ProcessAuthResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *payment.ProcessAuthRequest) (*payment.ProcessAuthResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *payment.ProcessAuthRequest) *payment.ProcessAuthResult); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.ProcessAuthResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *payment.ProcessAuthRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ProcessAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessAuth'
type MockService_ProcessAuth_Call struct {
	*mock.Call
}

// ProcessAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - req *payment.ProcessAuthRequest
func (_e *MockService_Expecter) ProcessAuth(ctx interface{}, req interface{}) *MockService_ProcessAuth_Call {
	return &MockService_ProcessAuth_Call{Call: _e.mock.On("ProcessAuth", ctx, req)}
}

func (_c *MockService_ProcessAuth_Call) Run(run func(ctx context.Context, req *payment.ProcessAuthRequest)) *MockService_ProcessAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*payment.ProcessAuthRequest))
	})
	return _c
}

func (_c *MockService_ProcessAuth_Call) Return(_a0 *payment.ProcessAuthResult, _a1 error) *MockService_ProcessAuth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ProcessAuth_Call) RunAndReturn(run func(context.Context, *payment.ProcessAuthRequest) (*payment.ProcessAuthResult, error)) *MockService_ProcessAuth_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyDomain provides a mock function with given fields: ctx, domain
func (_m *MockService) VerifyDomain(ctx context.Context, domain string) (bool, error) {
	ret := _m.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for VerifyDomain")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, domain)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, domain)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_VerifyDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyDomain'
type MockService_VerifyDomain_Call struct {
	*mock.Call
}

// VerifyDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
func (_e *MockService_Expecter) VerifyDomain(ctx interface{}, domain interface{}) *MockService_VerifyDomain_Call {
	return &MockService_VerifyDomain_Call{Call: _e.mock.On("VerifyDomain", ctx, domain)}
}

func (_c *MockService_VerifyDomain_Call) Run(run func(ctx context.Context, domain string)) *MockService_VerifyDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_VerifyDomain_Call) Return(_a0 bool, _a1 error) *MockService_VerifyDomain_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_VerifyDomain_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockService_VerifyDomain_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
