// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rbconsult-bh/saftaja/khazina/internal/app/payment"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// FinalizePayment provides a mock function for the type MockService
func (_mock *MockService) FinalizePayment(ctx context.Context, req *payment.FinalizePaymentRequest) (*payment.FinalizePaymentResult, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for FinalizePayment")
	}

	var r0 *payment.FinalizePaymentResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *payment.FinalizePaymentRequest) (*payment.FinalizePaymentResult, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *payment.FinalizePaymentRequest) *payment.FinalizePaymentResult); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.FinalizePaymentResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *payment.FinalizePaymentRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_FinalizePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinalizePayment'
type MockService_FinalizePayment_Call struct {
	*mock.Call
}

// FinalizePayment is a helper method to define mock.On call
//   - ctx context.Context
//   - req *payment.FinalizePaymentRequest
func (_e *MockService_Expecter) FinalizePayment(ctx interface{}, req interface{}) *MockService_FinalizePayment_Call {
	return &MockService_FinalizePayment_Call{Call: _e.mock.On("FinalizePayment", ctx, req)}
}

func (_c *MockService_FinalizePayment_Call) Run(run func(ctx context.Context, req *payment.FinalizePaymentRequest)) *MockService_FinalizePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *payment.FinalizePaymentRequest
		if args[1] != nil {
			arg1 = args[1].(*payment.FinalizePaymentRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_FinalizePayment_Call) Return(finalizePaymentResult *payment.FinalizePaymentResult, err error) *MockService_FinalizePayment_Call {
	_c.Call.Return(finalizePaymentResult, err)
	return _c
}

func (_c *MockService_FinalizePayment_Call) RunAndReturn(run func(ctx context.Context, req *payment.FinalizePaymentRequest) (*payment.FinalizePaymentResult, error)) *MockService_FinalizePayment_Call {
	_c.Call.Return(run)
	return _c
}

// InitiateAuth provides a mock function for the type MockService
func (_mock *MockService) InitiateAuth(ctx context.Context, req *payment.InitiateAuthRequest) (*payment.InitiateAuthResult, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for InitiateAuth")
	}

	var r0 *payment.InitiateAuthResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *payment.InitiateAuthRequest) (*payment.InitiateAuthResult, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *payment.InitiateAuthRequest) *payment.InitiateAuthResult); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.InitiateAuthResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *payment.InitiateAuthRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_InitiateAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitiateAuth'
type MockService_InitiateAuth_Call struct {
	*mock.Call
}

// InitiateAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - req *payment.InitiateAuthRequest
func (_e *MockService_Expecter) InitiateAuth(ctx interface{}, req interface{}) *MockService_InitiateAuth_Call {
	return &MockService_InitiateAuth_Call{Call: _e.mock.On("InitiateAuth", ctx, req)}
}

func (_c *MockService_InitiateAuth_Call) Run(run func(ctx context.Context, req *payment.InitiateAuthRequest)) *MockService_InitiateAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *payment.InitiateAuthRequest
		if args[1] != nil {
			arg1 = args[1].(*payment.InitiateAuthRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_InitiateAuth_Call) Return(initiateAuthResult *payment.InitiateAuthResult, err error) *MockService_InitiateAuth_Call {
	_c.Call.Return(initiateAuthResult, err)
	return _c
}

func (_c *MockService_InitiateAuth_Call) RunAndReturn(run func(ctx context.Context, req *payment.InitiateAuthRequest) (*payment.InitiateAuthResult, error)) *MockService_InitiateAuth_Call {
	_c.Call.Return(run)
	return _c
}

// InitiateSession provides a mock function for the type MockService
func (_mock *MockService) InitiateSession(ctx context.Context, req *payment.InitiateSessionRequest) (*payment.InitiateSessionResult, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for InitiateSession")
	}

	var r0 *payment.InitiateSessionResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *payment.InitiateSessionRequest) (*payment.InitiateSessionResult, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *payment.InitiateSessionRequest) *payment.InitiateSessionResult); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.InitiateSessionResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *payment.InitiateSessionRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_InitiateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitiateSession'
type MockService_InitiateSession_Call struct {
	*mock.Call
}

// InitiateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - req *payment.InitiateSessionRequest
func (_e *MockService_Expecter) InitiateSession(ctx interface{}, req interface{}) *MockService_InitiateSession_Call {
	return &MockService_InitiateSession_Call{Call: _e.mock.On("InitiateSession", ctx, req)}
}

func (_c *MockService_InitiateSession_Call) Run(run func(ctx context.Context, req *payment.InitiateSessionRequest)) *MockService_InitiateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *payment.InitiateSessionRequest
		if args[1] != nil {
			arg1 = args[1].(*payment.InitiateSessionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_InitiateSession_Call) Return(initiateSessionResult *payment.InitiateSessionResult, err error) *MockService_InitiateSession_Call {
	_c.Call.Return(initiateSessionResult, err)
	return _c
}

func (_c *MockService_InitiateSession_Call) RunAndReturn(run func(ctx context.Context, req *payment.InitiateSessionRequest) (*payment.InitiateSessionResult, error)) *MockService_InitiateSession_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessAuth provides a mock function for the type MockService
func (_mock *MockService) ProcessAuth(ctx context.Context, req *payment.ProcessAuthRequest) (*payment.ProcessAuthResult, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ProcessAuth")
	}

	var r0 *payment.ProcessAuthResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *payment.ProcessAuthRequest) (*payment.ProcessAuthResult, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *payment.ProcessAuthRequest) *payment.ProcessAuthResult); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.ProcessAuthResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *payment.ProcessAuthRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ProcessAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessAuth'
type MockService_ProcessAuth_Call struct {
	*mock.Call
}

// ProcessAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - req *payment.ProcessAuthRequest
func (_e *MockService_Expecter) ProcessAuth(ctx interface{}, req interface{}) *MockService_ProcessAuth_Call {
	return &MockService_ProcessAuth_Call{Call: _e.mock.On("ProcessAuth", ctx, req)}
}

func (_c *MockService_ProcessAuth_Call) Run(run func(ctx context.Context, req *payment.ProcessAuthRequest)) *MockService_ProcessAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *payment.ProcessAuthRequest
		if args[1] != nil {
			arg1 = args[1].(*payment.ProcessAuthRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ProcessAuth_Call) Return(processAuthResult *payment.ProcessAuthResult, err error) *MockService_ProcessAuth_Call {
	_c.Call.Return(processAuthResult, err)
	return _c
}

func (_c *MockService_ProcessAuth_Call) RunAndReturn(run func(ctx context.Context, req *payment.ProcessAuthRequest) (*payment.ProcessAuthResult, error)) *MockService_ProcessAuth_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyDomain provides a mock function for the type MockService
func (_mock *MockService) VerifyDomain(ctx context.Context, domain string) (bool, error) {
	ret := _mock.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for VerifyDomain")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, domain)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, domain)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_VerifyDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyDomain'
type MockService_VerifyDomain_Call struct {
	*mock.Call
}

// VerifyDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
func (_e *MockService_Expecter) VerifyDomain(ctx interface{}, domain interface{}) *MockService_VerifyDomain_Call {
	return &MockService_VerifyDomain_Call{Call: _e.mock.On("VerifyDomain", ctx, domain)}
}

func (_c *MockService_VerifyDomain_Call) Run(run func(ctx context.Context, domain string)) *MockService_VerifyDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_VerifyDomain_Call) Return(b bool, err error) *MockService_VerifyDomain_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockService_VerifyDomain_Call) RunAndReturn(run func(ctx context.Context, domain string) (bool, error)) *MockService_VerifyDomain_Call {
	_c.Call.Return(run)
	return _c
}
