// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: saftaja/dashboard/project/v1/project.proto

package projectpbv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/rbconsult-bh/saftaja/khazina/internal/transport/proto/saftaja/dashboard/project/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProjectServiceName is the fully-qualified name of the ProjectService service.
	ProjectServiceName = "saftaja.dashboard.project.v1.ProjectService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProjectServiceListGatewaysProcedure is the fully-qualified name of the ProjectService's
	// ListGateways RPC.
	ProjectServiceListGatewaysProcedure = "/saftaja.dashboard.project.v1.ProjectService/ListGateways"
	// ProjectServiceCreateGatewayProcedure is the fully-qualified name of the ProjectService's
	// CreateGateway RPC.
	ProjectServiceCreateGatewayProcedure = "/saftaja.dashboard.project.v1.ProjectService/CreateGateway"
)

// ProjectServiceClient is a client for the saftaja.dashboard.project.v1.ProjectService service.
type ProjectServiceClient interface {
	ListGateways(context.Context, *connect.Request[v1.ListGatewaysRequest]) (*connect.Response[v1.ListGatewaysResponse], error)
	CreateGateway(context.Context, *connect.Request[v1.CreateGatewayRequest]) (*connect.Response[v1.CreateGatewayResponse], error)
}

// NewProjectServiceClient constructs a client for the saftaja.dashboard.project.v1.ProjectService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProjectServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProjectServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	projectServiceMethods := v1.File_saftaja_dashboard_project_v1_project_proto.Services().ByName("ProjectService").Methods()
	return &projectServiceClient{
		listGateways: connect.NewClient[v1.ListGatewaysRequest, v1.ListGatewaysResponse](
			httpClient,
			baseURL+ProjectServiceListGatewaysProcedure,
			connect.WithSchema(projectServiceMethods.ByName("ListGateways")),
			connect.WithClientOptions(opts...),
		),
		createGateway: connect.NewClient[v1.CreateGatewayRequest, v1.CreateGatewayResponse](
			httpClient,
			baseURL+ProjectServiceCreateGatewayProcedure,
			connect.WithSchema(projectServiceMethods.ByName("CreateGateway")),
			connect.WithClientOptions(opts...),
		),
	}
}

// projectServiceClient implements ProjectServiceClient.
type projectServiceClient struct {
	listGateways  *connect.Client[v1.ListGatewaysRequest, v1.ListGatewaysResponse]
	createGateway *connect.Client[v1.CreateGatewayRequest, v1.CreateGatewayResponse]
}

// ListGateways calls saftaja.dashboard.project.v1.ProjectService.ListGateways.
func (c *projectServiceClient) ListGateways(ctx context.Context, req *connect.Request[v1.ListGatewaysRequest]) (*connect.Response[v1.ListGatewaysResponse], error) {
	return c.listGateways.CallUnary(ctx, req)
}

// CreateGateway calls saftaja.dashboard.project.v1.ProjectService.CreateGateway.
func (c *projectServiceClient) CreateGateway(ctx context.Context, req *connect.Request[v1.CreateGatewayRequest]) (*connect.Response[v1.CreateGatewayResponse], error) {
	return c.createGateway.CallUnary(ctx, req)
}

// ProjectServiceHandler is an implementation of the saftaja.dashboard.project.v1.ProjectService
// service.
type ProjectServiceHandler interface {
	ListGateways(context.Context, *connect.Request[v1.ListGatewaysRequest]) (*connect.Response[v1.ListGatewaysResponse], error)
	CreateGateway(context.Context, *connect.Request[v1.CreateGatewayRequest]) (*connect.Response[v1.CreateGatewayResponse], error)
}

// NewProjectServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProjectServiceHandler(svc ProjectServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	projectServiceMethods := v1.File_saftaja_dashboard_project_v1_project_proto.Services().ByName("ProjectService").Methods()
	projectServiceListGatewaysHandler := connect.NewUnaryHandler(
		ProjectServiceListGatewaysProcedure,
		svc.ListGateways,
		connect.WithSchema(projectServiceMethods.ByName("ListGateways")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceCreateGatewayHandler := connect.NewUnaryHandler(
		ProjectServiceCreateGatewayProcedure,
		svc.CreateGateway,
		connect.WithSchema(projectServiceMethods.ByName("CreateGateway")),
		connect.WithHandlerOptions(opts...),
	)
	return "/saftaja.dashboard.project.v1.ProjectService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProjectServiceListGatewaysProcedure:
			projectServiceListGatewaysHandler.ServeHTTP(w, r)
		case ProjectServiceCreateGatewayProcedure:
			projectServiceCreateGatewayHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProjectServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProjectServiceHandler struct{}

func (UnimplementedProjectServiceHandler) ListGateways(context.Context, *connect.Request[v1.ListGatewaysRequest]) (*connect.Response[v1.ListGatewaysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("saftaja.dashboard.project.v1.ProjectService.ListGateways is not implemented"))
}

func (UnimplementedProjectServiceHandler) CreateGateway(context.Context, *connect.Request[v1.CreateGatewayRequest]) (*connect.Response[v1.CreateGatewayResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("saftaja.dashboard.project.v1.ProjectService.CreateGateway is not implemented"))
}
