packages:
  github.com/rbconsult-bh/saftaja/khazina/internal/app/payment:
    interfaces:
      Service:
        config:
          dir: "internal/app/payment/mocks"
          outpkg: "mocks"
  github.com/rbconsult-bh/saftaja/khazina/internal/app/tenant:
    interfaces:
      Service:
        config:
          dir: "internal/app/tenant/mocks"
          outpkg: "mocks"
