packages:
  github.com/rbconsult-bh/saftaja/internal/payment:
    interfaces:
      Service:
        config:
          dir: "internal/payment/mocks"
          outpkg: "mocks"
  github.com/rbconsult-bh/saftaja/internal/tenant:
    interfaces:
      Service:
        config:
          dir: "internal/tenant/mocks"
          outpkg: "mocks"
