// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checkout.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    payment_session_id, invoice_id, project_id,
    transaction_type, gateway_transaction_id, amount, currency
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, payment_session_id, invoice_id, project_id, transaction_type, gateway_transaction_id, amount, currency, status, raw_request, raw_response, created_at, updated_at, deleted_at
`

type CreateTransactionParams struct {
	PaymentSessionID     uuid.UUID
	InvoiceID            uuid.UUID
	ProjectID            uuid.UUID
	TransactionType      TransactionTransactionType
	GatewayTransactionID string
	Amount               decimal.Decimal
	Currency             string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.PaymentSessionID,
		arg.InvoiceID,
		arg.ProjectID,
		arg.TransactionType,
		arg.GatewayTransactionID,
		arg.Amount,
		arg.Currency,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.PaymentSessionID,
		&i.InvoiceID,
		&i.ProjectID,
		&i.TransactionType,
		&i.GatewayTransactionID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.RawRequest,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGatewayAccount = `-- name: GetGatewayAccount :one
SELECT id, project_id, connector_type, account_name, credentials, settings, payment_methods, is_active, created_at, updated_at, deleted_at FROM gateway_accounts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGatewayAccount(ctx context.Context, id uuid.UUID) (GatewayAccount, error) {
	row := q.db.QueryRow(ctx, getGatewayAccount, id)
	var i GatewayAccount
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ConnectorType,
		&i.AccountName,
		&i.Credentials,
		&i.Settings,
		&i.PaymentMethods,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGatewayAccountByPaymentSessionID = `-- name: GetGatewayAccountByPaymentSessionID :one
SELECT ga.id, ga.project_id, connector_type, account_name, credentials, settings, payment_methods, is_active, ga.created_at, ga.updated_at, ga.deleted_at, ps.id, invoice_id, ps.project_id, gateway_account_id, gateway_session_id, status, payment_method, payer_ip, payer_user_agent, expires_at, ps.created_at, ps.updated_at, ps.deleted_at FROM gateway_accounts ga
JOIN payment_sessions ps ON ga.id = ps.gateway_account_id
WHERE ps.id = $1
`

type GetGatewayAccountByPaymentSessionIDRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	ConnectorType    GatewayAccountConnectorType
	AccountName      string
	Credentials      []byte
	Settings         []byte
	PaymentMethods   []byte
	IsActive         bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	ID_2             uuid.UUID
	InvoiceID        uuid.UUID
	ProjectID_2      uuid.UUID
	GatewayAccountID uuid.UUID
	GatewaySessionID string
	Status           PaymentSessionStatus
	PaymentMethod    PaymentSessionPaymentMethod
	PayerIp          pgtype.Text
	PayerUserAgent   pgtype.Text
	ExpiresAt        pgtype.Timestamptz
	CreatedAt_2      pgtype.Timestamptz
	UpdatedAt_2      pgtype.Timestamptz
	DeletedAt_2      pgtype.Timestamptz
}

func (q *Queries) GetGatewayAccountByPaymentSessionID(ctx context.Context, id uuid.UUID) (GetGatewayAccountByPaymentSessionIDRow, error) {
	row := q.db.QueryRow(ctx, getGatewayAccountByPaymentSessionID, id)
	var i GetGatewayAccountByPaymentSessionIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ConnectorType,
		&i.AccountName,
		&i.Credentials,
		&i.Settings,
		&i.PaymentMethods,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ID_2,
		&i.InvoiceID,
		&i.ProjectID_2,
		&i.GatewayAccountID,
		&i.GatewaySessionID,
		&i.Status,
		&i.PaymentMethod,
		&i.PayerIp,
		&i.PayerUserAgent,
		&i.ExpiresAt,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
		&i.DeletedAt_2,
	)
	return i, err
}

const getLatestPaymentSession = `-- name: GetLatestPaymentSession :one
SELECT id, invoice_id, project_id, gateway_account_id, gateway_session_id, status, payment_method, payer_ip, payer_user_agent, expires_at, created_at, updated_at, deleted_at FROM payment_sessions
WHERE invoice_id = $1
AND status IN ('created', 'authenticating', 'authenticated')
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestPaymentSession(ctx context.Context, invoiceID uuid.UUID) (PaymentSession, error) {
	row := q.db.QueryRow(ctx, getLatestPaymentSession, invoiceID)
	var i PaymentSession
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ProjectID,
		&i.GatewayAccountID,
		&i.GatewaySessionID,
		&i.Status,
		&i.PaymentMethod,
		&i.PayerIp,
		&i.PayerUserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLatestTransaction = `-- name: GetLatestTransaction :one
SELECT id, payment_session_id, invoice_id, project_id, transaction_type, gateway_transaction_id, amount, currency, status, raw_request, raw_response, created_at, updated_at, deleted_at FROM transactions
WHERE payment_session_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestTransaction(ctx context.Context, paymentSessionID uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getLatestTransaction, paymentSessionID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.PaymentSessionID,
		&i.InvoiceID,
		&i.ProjectID,
		&i.TransactionType,
		&i.GatewayTransactionID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.RawRequest,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPaymentSessionByID = `-- name: GetPaymentSessionByID :one
SELECT id, invoice_id, project_id, gateway_account_id, gateway_session_id, status, payment_method, payer_ip, payer_user_agent, expires_at, created_at, updated_at, deleted_at FROM payment_sessions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPaymentSessionByID(ctx context.Context, id uuid.UUID) (PaymentSession, error) {
	row := q.db.QueryRow(ctx, getPaymentSessionByID, id)
	var i PaymentSession
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ProjectID,
		&i.GatewayAccountID,
		&i.GatewaySessionID,
		&i.Status,
		&i.PaymentMethod,
		&i.PayerIp,
		&i.PayerUserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByPaymentSessionID = `-- name: GetProjectByPaymentSessionID :one
SELECT p.id, organization_id, name, environment, custom_domain, p.created_at, p.updated_at, p.deleted_at, ps.id, invoice_id, project_id, gateway_account_id, gateway_session_id, status, payment_method, payer_ip, payer_user_agent, expires_at, ps.created_at, ps.updated_at, ps.deleted_at FROM projects p
JOIN payment_sessions ps ON p.id = ps.project_id
WHERE ps.id = $1
`

type GetProjectByPaymentSessionIDRow struct {
	ID               uuid.UUID
	OrganizationID   uuid.UUID
	Name             string
	Environment      ProjectEnvironment
	CustomDomain     pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	ID_2             uuid.UUID
	InvoiceID        uuid.UUID
	ProjectID        uuid.UUID
	GatewayAccountID uuid.UUID
	GatewaySessionID string
	Status           PaymentSessionStatus
	PaymentMethod    PaymentSessionPaymentMethod
	PayerIp          pgtype.Text
	PayerUserAgent   pgtype.Text
	ExpiresAt        pgtype.Timestamptz
	CreatedAt_2      pgtype.Timestamptz
	UpdatedAt_2      pgtype.Timestamptz
	DeletedAt_2      pgtype.Timestamptz
}

func (q *Queries) GetProjectByPaymentSessionID(ctx context.Context, id uuid.UUID) (GetProjectByPaymentSessionIDRow, error) {
	row := q.db.QueryRow(ctx, getProjectByPaymentSessionID, id)
	var i GetProjectByPaymentSessionIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Environment,
		&i.CustomDomain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ID_2,
		&i.InvoiceID,
		&i.ProjectID,
		&i.GatewayAccountID,
		&i.GatewaySessionID,
		&i.Status,
		&i.PaymentMethod,
		&i.PayerIp,
		&i.PayerUserAgent,
		&i.ExpiresAt,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
		&i.DeletedAt_2,
	)
	return i, err
}

const getSuccessfulAuthTransaction = `-- name: GetSuccessfulAuthTransaction :one
SELECT id, payment_session_id, invoice_id, project_id, transaction_type, gateway_transaction_id, amount, currency, status, raw_request, raw_response, created_at, updated_at, deleted_at FROM transactions
WHERE payment_session_id = $1
AND transaction_type = 'authenticate_payer'
AND status = 'success'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetSuccessfulAuthTransaction(ctx context.Context, paymentSessionID uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getSuccessfulAuthTransaction, paymentSessionID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.PaymentSessionID,
		&i.InvoiceID,
		&i.ProjectID,
		&i.TransactionType,
		&i.GatewayTransactionID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.RawRequest,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveGatewayAccounts = `-- name: ListActiveGatewayAccounts :many
SELECT id, project_id, connector_type, account_name, credentials, settings, payment_methods, is_active, created_at, updated_at, deleted_at FROM gateway_accounts
WHERE project_id = $1
AND is_active = true
AND deleted_at IS NULL
`

func (q *Queries) ListActiveGatewayAccounts(ctx context.Context, projectID uuid.UUID) ([]GatewayAccount, error) {
	rows, err := q.db.Query(ctx, listActiveGatewayAccounts, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GatewayAccount
	for rows.Next() {
		var i GatewayAccount
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ConnectorType,
			&i.AccountName,
			&i.Credentials,
			&i.Settings,
			&i.PaymentMethods,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentSessionGatewayID = `-- name: UpdatePaymentSessionGatewayID :exec
UPDATE payment_sessions
SET gateway_session_id = $2
WHERE id = $1
`

type UpdatePaymentSessionGatewayIDParams struct {
	ID               uuid.UUID
	GatewaySessionID string
}

func (q *Queries) UpdatePaymentSessionGatewayID(ctx context.Context, arg UpdatePaymentSessionGatewayIDParams) error {
	_, err := q.db.Exec(ctx, updatePaymentSessionGatewayID, arg.ID, arg.GatewaySessionID)
	return err
}

const updatePaymentSessionStatus = `-- name: UpdatePaymentSessionStatus :exec
UPDATE payment_sessions
SET status = $2
WHERE id = $1
`

type UpdatePaymentSessionStatusParams struct {
	ID     uuid.UUID
	Status PaymentSessionStatus
}

func (q *Queries) UpdatePaymentSessionStatus(ctx context.Context, arg UpdatePaymentSessionStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentSessionStatus, arg.ID, arg.Status)
	return err
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :exec
UPDATE transactions
SET status = $2, raw_response = $3
WHERE id = $1
`

type UpdateTransactionStatusParams struct {
	ID          uuid.UUID
	Status      TransactionStatus
	RawResponse []byte
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) error {
	_, err := q.db.Exec(ctx, updateTransactionStatus, arg.ID, arg.Status, arg.RawResponse)
	return err
}
