// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GatewayConfig struct {
	ID          pgtype.UUID
	ProjectID   pgtype.UUID
	Name        string
	GatewayType string
	BaseUrl     string
	MerchantID  string
	ApiPassword string
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type Invoice struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	Amount        pgtype.Numeric
	Currency      string
	Status        string
	ExternalID    pgtype.Text
	CustomerEmail pgtype.Text
	CustomerName  pgtype.Text
	Description   pgtype.Text
	PaidAt        pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type Organization struct {
	ID        pgtype.UUID
	Name      string
	Subdomain pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type PaymentSession struct {
	ID               pgtype.UUID
	InvoiceID        pgtype.UUID
	ProjectID        pgtype.UUID
	GatewayConfigID  pgtype.UUID
	GatewaySessionID string
	Status           string
	PaymentMethod    string
	PayerIp          pgtype.Text
	PayerUserAgent   pgtype.Text
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type Project struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	Environment    string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type Transaction struct {
	ID               pgtype.UUID
	PaymentSessionID pgtype.UUID
	InvoiceID        pgtype.UUID
	ProjectID        pgtype.UUID
	TransactionType  string
	Amount           pgtype.Numeric
	Currency         string
	Status           string
	RawRequest       []byte
	RawResponse      []byte
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}
