// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: saftaja/dashboard/auth/v1/auth.proto

package authpbv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/rbconsult-bh/saftaja/khazina/internal/transport/proto/saftaja/dashboard/auth/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "saftaja.dashboard.auth.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceInitiateAuthProcedure is the fully-qualified name of the AuthService's InitiateAuth
	// RPC.
	AuthServiceInitiateAuthProcedure = "/saftaja.dashboard.auth.v1.AuthService/InitiateAuth"
	// AuthServiceCompleteAuthProcedure is the fully-qualified name of the AuthService's CompleteAuth
	// RPC.
	AuthServiceCompleteAuthProcedure = "/saftaja.dashboard.auth.v1.AuthService/CompleteAuth"
	// AuthServiceRefreshTokenProcedure is the fully-qualified name of the AuthService's RefreshToken
	// RPC.
	AuthServiceRefreshTokenProcedure = "/saftaja.dashboard.auth.v1.AuthService/RefreshToken"
	// AuthServiceLogoutProcedure is the fully-qualified name of the AuthService's Logout RPC.
	AuthServiceLogoutProcedure = "/saftaja.dashboard.auth.v1.AuthService/Logout"
)

// AuthServiceClient is a client for the saftaja.dashboard.auth.v1.AuthService service.
type AuthServiceClient interface {
	InitiateAuth(context.Context, *connect.Request[v1.InitiateAuthRequest]) (*connect.Response[v1.InitiateAuthResponse], error)
	CompleteAuth(context.Context, *connect.Request[v1.CompleteAuthRequest]) (*connect.Response[v1.CompleteAuthResponse], error)
	RefreshToken(context.Context, *connect.Request[v1.RefreshTokenRequest]) (*connect.Response[v1.RefreshTokenResponse], error)
	Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error)
}

// NewAuthServiceClient constructs a client for the saftaja.dashboard.auth.v1.AuthService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1.File_saftaja_dashboard_auth_v1_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		initiateAuth: connect.NewClient[v1.InitiateAuthRequest, v1.InitiateAuthResponse](
			httpClient,
			baseURL+AuthServiceInitiateAuthProcedure,
			connect.WithSchema(authServiceMethods.ByName("InitiateAuth")),
			connect.WithClientOptions(opts...),
		),
		completeAuth: connect.NewClient[v1.CompleteAuthRequest, v1.CompleteAuthResponse](
			httpClient,
			baseURL+AuthServiceCompleteAuthProcedure,
			connect.WithSchema(authServiceMethods.ByName("CompleteAuth")),
			connect.WithClientOptions(opts...),
		),
		refreshToken: connect.NewClient[v1.RefreshTokenRequest, v1.RefreshTokenResponse](
			httpClient,
			baseURL+AuthServiceRefreshTokenProcedure,
			connect.WithSchema(authServiceMethods.ByName("RefreshToken")),
			connect.WithClientOptions(opts...),
		),
		logout: connect.NewClient[v1.LogoutRequest, v1.LogoutResponse](
			httpClient,
			baseURL+AuthServiceLogoutProcedure,
			connect.WithSchema(authServiceMethods.ByName("Logout")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	initiateAuth *connect.Client[v1.InitiateAuthRequest, v1.InitiateAuthResponse]
	completeAuth *connect.Client[v1.CompleteAuthRequest, v1.CompleteAuthResponse]
	refreshToken *connect.Client[v1.RefreshTokenRequest, v1.RefreshTokenResponse]
	logout       *connect.Client[v1.LogoutRequest, v1.LogoutResponse]
}

// InitiateAuth calls saftaja.dashboard.auth.v1.AuthService.InitiateAuth.
func (c *authServiceClient) InitiateAuth(ctx context.Context, req *connect.Request[v1.InitiateAuthRequest]) (*connect.Response[v1.InitiateAuthResponse], error) {
	return c.initiateAuth.CallUnary(ctx, req)
}

// CompleteAuth calls saftaja.dashboard.auth.v1.AuthService.CompleteAuth.
func (c *authServiceClient) CompleteAuth(ctx context.Context, req *connect.Request[v1.CompleteAuthRequest]) (*connect.Response[v1.CompleteAuthResponse], error) {
	return c.completeAuth.CallUnary(ctx, req)
}

// RefreshToken calls saftaja.dashboard.auth.v1.AuthService.RefreshToken.
func (c *authServiceClient) RefreshToken(ctx context.Context, req *connect.Request[v1.RefreshTokenRequest]) (*connect.Response[v1.RefreshTokenResponse], error) {
	return c.refreshToken.CallUnary(ctx, req)
}

// Logout calls saftaja.dashboard.auth.v1.AuthService.Logout.
func (c *authServiceClient) Logout(ctx context.Context, req *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error) {
	return c.logout.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the saftaja.dashboard.auth.v1.AuthService service.
type AuthServiceHandler interface {
	InitiateAuth(context.Context, *connect.Request[v1.InitiateAuthRequest]) (*connect.Response[v1.InitiateAuthResponse], error)
	CompleteAuth(context.Context, *connect.Request[v1.CompleteAuthRequest]) (*connect.Response[v1.CompleteAuthResponse], error)
	RefreshToken(context.Context, *connect.Request[v1.RefreshTokenRequest]) (*connect.Response[v1.RefreshTokenResponse], error)
	Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1.File_saftaja_dashboard_auth_v1_auth_proto.Services().ByName("AuthService").Methods()
	authServiceInitiateAuthHandler := connect.NewUnaryHandler(
		AuthServiceInitiateAuthProcedure,
		svc.InitiateAuth,
		connect.WithSchema(authServiceMethods.ByName("InitiateAuth")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceCompleteAuthHandler := connect.NewUnaryHandler(
		AuthServiceCompleteAuthProcedure,
		svc.CompleteAuth,
		connect.WithSchema(authServiceMethods.ByName("CompleteAuth")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRefreshTokenHandler := connect.NewUnaryHandler(
		AuthServiceRefreshTokenProcedure,
		svc.RefreshToken,
		connect.WithSchema(authServiceMethods.ByName("RefreshToken")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceLogoutHandler := connect.NewUnaryHandler(
		AuthServiceLogoutProcedure,
		svc.Logout,
		connect.WithSchema(authServiceMethods.ByName("Logout")),
		connect.WithHandlerOptions(opts...),
	)
	return "/saftaja.dashboard.auth.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceInitiateAuthProcedure:
			authServiceInitiateAuthHandler.ServeHTTP(w, r)
		case AuthServiceCompleteAuthProcedure:
			authServiceCompleteAuthHandler.ServeHTTP(w, r)
		case AuthServiceRefreshTokenProcedure:
			authServiceRefreshTokenHandler.ServeHTTP(w, r)
		case AuthServiceLogoutProcedure:
			authServiceLogoutHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) InitiateAuth(context.Context, *connect.Request[v1.InitiateAuthRequest]) (*connect.Response[v1.InitiateAuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("saftaja.dashboard.auth.v1.AuthService.InitiateAuth is not implemented"))
}

func (UnimplementedAuthServiceHandler) CompleteAuth(context.Context, *connect.Request[v1.CompleteAuthRequest]) (*connect.Response[v1.CompleteAuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("saftaja.dashboard.auth.v1.AuthService.CompleteAuth is not implemented"))
}

func (UnimplementedAuthServiceHandler) RefreshToken(context.Context, *connect.Request[v1.RefreshTokenRequest]) (*connect.Response[v1.RefreshTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("saftaja.dashboard.auth.v1.AuthService.RefreshToken is not implemented"))
}

func (UnimplementedAuthServiceHandler) Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("saftaja.dashboard.auth.v1.AuthService.Logout is not implemented"))
}
