// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rbconsult-bh/saftaja/khazina/internal/app/gateway"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, req gateway.CreateGatewayRequest) (*gateway.GatewayAccount, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *gateway.GatewayAccount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gateway.CreateGatewayRequest) (*gateway.GatewayAccount, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gateway.CreateGatewayRequest) *gateway.GatewayAccount); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.GatewayAccount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gateway.CreateGatewayRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req gateway.CreateGatewayRequest
func (_e *MockService_Expecter) Create(ctx interface{}, req interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, req gateway.CreateGatewayRequest)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gateway.CreateGatewayRequest
		if args[1] != nil {
			arg1 = args[1].(gateway.CreateGatewayRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(gatewayAccount *gateway.GatewayAccount, err error) *MockService_Create_Call {
	_c.Call.Return(gatewayAccount, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, req gateway.CreateGatewayRequest) (*gateway.GatewayAccount, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveByProject provides a mock function for the type MockService
func (_mock *MockService) ListActiveByProject(ctx context.Context, r gateway.ListActiveByProjectRequest) (*gateway.ListActiveByProjectResponse, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveByProject")
	}

	var r0 *gateway.ListActiveByProjectResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gateway.ListActiveByProjectRequest) (*gateway.ListActiveByProjectResponse, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gateway.ListActiveByProjectRequest) *gateway.ListActiveByProjectResponse); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.ListActiveByProjectResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gateway.ListActiveByProjectRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListActiveByProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveByProject'
type MockService_ListActiveByProject_Call struct {
	*mock.Call
}

// ListActiveByProject is a helper method to define mock.On call
//   - ctx context.Context
//   - r gateway.ListActiveByProjectRequest
func (_e *MockService_Expecter) ListActiveByProject(ctx interface{}, r interface{}) *MockService_ListActiveByProject_Call {
	return &MockService_ListActiveByProject_Call{Call: _e.mock.On("ListActiveByProject", ctx, r)}
}

func (_c *MockService_ListActiveByProject_Call) Run(run func(ctx context.Context, r gateway.ListActiveByProjectRequest)) *MockService_ListActiveByProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gateway.ListActiveByProjectRequest
		if args[1] != nil {
			arg1 = args[1].(gateway.ListActiveByProjectRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ListActiveByProject_Call) Return(listActiveByProjectResponse *gateway.ListActiveByProjectResponse, err error) *MockService_ListActiveByProject_Call {
	_c.Call.Return(listActiveByProjectResponse, err)
	return _c
}

func (_c *MockService_ListActiveByProject_Call) RunAndReturn(run func(ctx context.Context, r gateway.ListActiveByProjectRequest) (*gateway.ListActiveByProjectResponse, error)) *MockService_ListActiveByProject_Call {
	_c.Call.Return(run)
	return _c
}

// ListPaymentMethods provides a mock function for the type MockService
func (_mock *MockService) ListPaymentMethods(ctx context.Context, r gateway.ListPaymentMethodsRequest) (*gateway.ListPaymentMethodsResponse, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for ListPaymentMethods")
	}

	var r0 *gateway.ListPaymentMethodsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gateway.ListPaymentMethodsRequest) (*gateway.ListPaymentMethodsResponse, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gateway.ListPaymentMethodsRequest) *gateway.ListPaymentMethodsResponse); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.ListPaymentMethodsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gateway.ListPaymentMethodsRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListPaymentMethods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPaymentMethods'
type MockService_ListPaymentMethods_Call struct {
	*mock.Call
}

// ListPaymentMethods is a helper method to define mock.On call
//   - ctx context.Context
//   - r gateway.ListPaymentMethodsRequest
func (_e *MockService_Expecter) ListPaymentMethods(ctx interface{}, r interface{}) *MockService_ListPaymentMethods_Call {
	return &MockService_ListPaymentMethods_Call{Call: _e.mock.On("ListPaymentMethods", ctx, r)}
}

func (_c *MockService_ListPaymentMethods_Call) Run(run func(ctx context.Context, r gateway.ListPaymentMethodsRequest)) *MockService_ListPaymentMethods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gateway.ListPaymentMethodsRequest
		if args[1] != nil {
			arg1 = args[1].(gateway.ListPaymentMethodsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ListPaymentMethods_Call) Return(listPaymentMethodsResponse *gateway.ListPaymentMethodsResponse, err error) *MockService_ListPaymentMethods_Call {
	_c.Call.Return(listPaymentMethodsResponse, err)
	return _c
}

func (_c *MockService_ListPaymentMethods_Call) RunAndReturn(run func(ctx context.Context, r gateway.ListPaymentMethodsRequest) (*gateway.ListPaymentMethodsResponse, error)) *MockService_ListPaymentMethods_Call {
	_c.Call.Return(run)
	return _c
}
