// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/rbconsult-bh/saftaja/khazina/internal/app/gateway"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// ListActiveByProject provides a mock function for the type MockService
func (_mock *MockService) ListActiveByProject(ctx context.Context, projectID uuid.UUID) ([]gateway.GatewayCredentials, error) {
	ret := _mock.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveByProject")
	}

	var r0 []gateway.GatewayCredentials
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]gateway.GatewayCredentials, error)); ok {
		return returnFunc(ctx, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []gateway.GatewayCredentials); ok {
		r0 = returnFunc(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gateway.GatewayCredentials)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListActiveByProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveByProject'
type MockService_ListActiveByProject_Call struct {
	*mock.Call
}

// ListActiveByProject is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
func (_e *MockService_Expecter) ListActiveByProject(ctx interface{}, projectID interface{}) *MockService_ListActiveByProject_Call {
	return &MockService_ListActiveByProject_Call{Call: _e.mock.On("ListActiveByProject", ctx, projectID)}
}

func (_c *MockService_ListActiveByProject_Call) Run(run func(ctx context.Context, projectID uuid.UUID)) *MockService_ListActiveByProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ListActiveByProject_Call) Return(gatewayCredentialss []gateway.GatewayCredentials, err error) *MockService_ListActiveByProject_Call {
	_c.Call.Return(gatewayCredentialss, err)
	return _c
}

func (_c *MockService_ListActiveByProject_Call) RunAndReturn(run func(ctx context.Context, projectID uuid.UUID) ([]gateway.GatewayCredentials, error)) *MockService_ListActiveByProject_Call {
	_c.Call.Return(run)
	return _c
}
