// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: saftaja/dashboard/auth/v1/auth.proto

package authpbv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitiateAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateAuthRequest) Reset() {
	*x = InitiateAuthRequest{}
	mi := &file_saftaja_dashboard_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateAuthRequest) ProtoMessage() {}

func (x *InitiateAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saftaja_dashboard_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateAuthRequest.ProtoReflect.Descriptor instead.
func (*InitiateAuthRequest) Descriptor() ([]byte, []int) {
	return file_saftaja_dashboard_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *InitiateAuthRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type InitiateAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateAuthResponse) Reset() {
	*x = InitiateAuthResponse{}
	mi := &file_saftaja_dashboard_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateAuthResponse) ProtoMessage() {}

func (x *InitiateAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saftaja_dashboard_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateAuthResponse.ProtoReflect.Descriptor instead.
func (*InitiateAuthResponse) Descriptor() ([]byte, []int) {
	return file_saftaja_dashboard_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

type CompleteAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteAuthRequest) Reset() {
	*x = CompleteAuthRequest{}
	mi := &file_saftaja_dashboard_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteAuthRequest) ProtoMessage() {}

func (x *CompleteAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saftaja_dashboard_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteAuthRequest.ProtoReflect.Descriptor instead.
func (*CompleteAuthRequest) Descriptor() ([]byte, []int) {
	return file_saftaja_dashboard_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteAuthRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CompleteAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteAuthResponse) Reset() {
	*x = CompleteAuthResponse{}
	mi := &file_saftaja_dashboard_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteAuthResponse) ProtoMessage() {}

func (x *CompleteAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saftaja_dashboard_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteAuthResponse.ProtoReflect.Descriptor instead.
func (*CompleteAuthResponse) Descriptor() ([]byte, []int) {
	return file_saftaja_dashboard_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteAuthResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CompleteAuthResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_saftaja_dashboard_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saftaja_dashboard_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_saftaja_dashboard_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_saftaja_dashboard_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saftaja_dashboard_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_saftaja_dashboard_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_saftaja_dashboard_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saftaja_dashboard_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_saftaja_dashboard_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_saftaja_dashboard_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saftaja_dashboard_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_saftaja_dashboard_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

var File_saftaja_dashboard_auth_v1_auth_proto protoreflect.FileDescriptor

const file_saftaja_dashboard_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"$saftaja/dashboard/auth/v1/auth.proto\x12\x19saftaja.dashboard.auth.v1\x1a\x1bbuf/validate/validate.proto\"y\n" +
	"\x13InitiateAuthRequest\x12b\n" +
	"\x05email\x18\x01 \x01(\tBL\xbaHI\xba\x01F\n" +
	"\x0finit_auth.email\x12#InitAuthRequest email must be valid\x1a\x0ethis.isEmail()R\x05email\"\x16\n" +
	"\x14InitiateAuthResponse\"+\n" +
	"\x13CompleteAuthRequest\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"^\n" +
	"\x14CompleteAuthResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"^\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"\x0f\n" +
	"\rLogoutRequest\"\x10\n" +
	"\x0eLogoutResponse2\xbf\x03\n" +
	"\vAuthService\x12o\n" +
	"\fInitiateAuth\x12..saftaja.dashboard.auth.v1.InitiateAuthRequest\x1a/.saftaja.dashboard.auth.v1.InitiateAuthResponse\x12o\n" +
	"\fCompleteAuth\x12..saftaja.dashboard.auth.v1.CompleteAuthRequest\x1a/.saftaja.dashboard.auth.v1.CompleteAuthResponse\x12o\n" +
	"\fRefreshToken\x12..saftaja.dashboard.auth.v1.RefreshTokenRequest\x1a/.saftaja.dashboard.auth.v1.RefreshTokenResponse\x12]\n" +
	"\x06Logout\x12(.saftaja.dashboard.auth.v1.LogoutRequest\x1a).saftaja.dashboard.auth.v1.LogoutResponseBeZcgithub.com/rbconsult-bh/saftaja/khazina/internal/transport/proto/saftaja/dashboard/auth/v1;authpbv1b\x06proto3"

var (
	file_saftaja_dashboard_auth_v1_auth_proto_rawDescOnce sync.Once
	file_saftaja_dashboard_auth_v1_auth_proto_rawDescData []byte
)

func file_saftaja_dashboard_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_saftaja_dashboard_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_saftaja_dashboard_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_saftaja_dashboard_auth_v1_auth_proto_rawDesc), len(file_saftaja_dashboard_auth_v1_auth_proto_rawDesc)))
	})
	return file_saftaja_dashboard_auth_v1_auth_proto_rawDescData
}

var file_saftaja_dashboard_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_saftaja_dashboard_auth_v1_auth_proto_goTypes = []any{
	(*InitiateAuthRequest)(nil),  // 0: saftaja.dashboard.auth.v1.InitiateAuthRequest
	(*InitiateAuthResponse)(nil), // 1: saftaja.dashboard.auth.v1.InitiateAuthResponse
	(*CompleteAuthRequest)(nil),  // 2: saftaja.dashboard.auth.v1.CompleteAuthRequest
	(*CompleteAuthResponse)(nil), // 3: saftaja.dashboard.auth.v1.CompleteAuthResponse
	(*RefreshTokenRequest)(nil),  // 4: saftaja.dashboard.auth.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil), // 5: saftaja.dashboard.auth.v1.RefreshTokenResponse
	(*LogoutRequest)(nil),        // 6: saftaja.dashboard.auth.v1.LogoutRequest
	(*LogoutResponse)(nil),       // 7: saftaja.dashboard.auth.v1.LogoutResponse
}
var file_saftaja_dashboard_auth_v1_auth_proto_depIdxs = []int32{
	0, // 0: saftaja.dashboard.auth.v1.AuthService.InitiateAuth:input_type -> saftaja.dashboard.auth.v1.InitiateAuthRequest
	2, // 1: saftaja.dashboard.auth.v1.AuthService.CompleteAuth:input_type -> saftaja.dashboard.auth.v1.CompleteAuthRequest
	4, // 2: saftaja.dashboard.auth.v1.AuthService.RefreshToken:input_type -> saftaja.dashboard.auth.v1.RefreshTokenRequest
	6, // 3: saftaja.dashboard.auth.v1.AuthService.Logout:input_type -> saftaja.dashboard.auth.v1.LogoutRequest
	1, // 4: saftaja.dashboard.auth.v1.AuthService.InitiateAuth:output_type -> saftaja.dashboard.auth.v1.InitiateAuthResponse
	3, // 5: saftaja.dashboard.auth.v1.AuthService.CompleteAuth:output_type -> saftaja.dashboard.auth.v1.CompleteAuthResponse
	5, // 6: saftaja.dashboard.auth.v1.AuthService.RefreshToken:output_type -> saftaja.dashboard.auth.v1.RefreshTokenResponse
	7, // 7: saftaja.dashboard.auth.v1.AuthService.Logout:output_type -> saftaja.dashboard.auth.v1.LogoutResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_saftaja_dashboard_auth_v1_auth_proto_init() }
func file_saftaja_dashboard_auth_v1_auth_proto_init() {
	if File_saftaja_dashboard_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_saftaja_dashboard_auth_v1_auth_proto_rawDesc), len(file_saftaja_dashboard_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_saftaja_dashboard_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_saftaja_dashboard_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_saftaja_dashboard_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_saftaja_dashboard_auth_v1_auth_proto = out.File
	file_saftaja_dashboard_auth_v1_auth_proto_goTypes = nil
	file_saftaja_dashboard_auth_v1_auth_proto_depIdxs = nil
}
