name: Build Khazina

on:
  push:
    branches: [main]
    paths:
      - 'khazina/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yaml

  build:
    needs: test
    uses: ./.github/workflows/reusable-build.yaml
    secrets: inherit
    with:
      image_name: khazina
      context_path: ./khazina

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
