name: Run E2E Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: oven-sh/setup-bun@b7a1c7ccf290d58743029c4f6903da283811b979 # v2.1.0
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: khazina/tests/e2e
        run: bun install --frozen-lockfile

      - name: Install Playwright Browsers
        working-directory: khazina/tests/e2e
        run: bun run playwright install --with-deps

      - name: Run Playwright tests
        working-directory: khazina/tests/e2e
        run: bun run playwright test -j 1
        env:
          TEST_MPGS_BASE_URL: ${{ secrets.TEST_MPGS_BASE_URL }}
          TEST_MPGS_MERCHANT_ID: ${{ secrets.TEST_MPGS_MERCHANT_ID }}
          TEST_MPGS_API_PASSWORD: ${{ secrets.TEST_MPGS_API_PASSWORD }}
          CI: true

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: always()
        with:
          name: e2e-debug-bundle
          path: khazina/tests/e2e/playwright-report/
          retention-days: 30
